// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/client/player/heartbeat.proto
// Protobuf C++ Version: 6.32.1

#ifndef proto_2fclient_2fplayer_2fheartbeat_2eproto_2epb_2eh
#define proto_2fclient_2fplayer_2fheartbeat_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6032001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_proto_2fclient_2fplayer_2fheartbeat_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2fclient_2fplayer_2fheartbeat_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_proto_2fclient_2fplayer_2fheartbeat_2eproto;
}  // extern "C"
namespace celeritas {
namespace proto {
namespace client {
class client_heartbeat_request;
struct client_heartbeat_requestDefaultTypeInternal;
extern client_heartbeat_requestDefaultTypeInternal _client_heartbeat_request_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull client_heartbeat_request_class_data_;
class client_heartbeat_response;
struct client_heartbeat_responseDefaultTypeInternal;
extern client_heartbeat_responseDefaultTypeInternal _client_heartbeat_response_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull client_heartbeat_response_class_data_;
}  // namespace client
}  // namespace proto
}  // namespace celeritas
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace celeritas {
namespace proto {
namespace client {

// ===================================================================


// -------------------------------------------------------------------

class client_heartbeat_response final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:celeritas.proto.client.client_heartbeat_response) */ {
 public:
  inline client_heartbeat_response() : client_heartbeat_response(nullptr) {}
  ~client_heartbeat_response() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(client_heartbeat_response* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(client_heartbeat_response));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR client_heartbeat_response(::google::protobuf::internal::ConstantInitialized);

  inline client_heartbeat_response(const client_heartbeat_response& from) : client_heartbeat_response(nullptr, from) {}
  inline client_heartbeat_response(client_heartbeat_response&& from) noexcept
      : client_heartbeat_response(nullptr, ::std::move(from)) {}
  inline client_heartbeat_response& operator=(const client_heartbeat_response& from) {
    CopyFrom(from);
    return *this;
  }
  inline client_heartbeat_response& operator=(client_heartbeat_response&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const client_heartbeat_response& default_instance() {
    return *reinterpret_cast<const client_heartbeat_response*>(
        &_client_heartbeat_response_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(client_heartbeat_response& a, client_heartbeat_response& b) { a.Swap(&b); }
  inline void Swap(client_heartbeat_response* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(client_heartbeat_response* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  client_heartbeat_response* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<client_heartbeat_response>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const client_heartbeat_response& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const client_heartbeat_response& from) { client_heartbeat_response::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(client_heartbeat_response* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "celeritas.proto.client.client_heartbeat_response"; }

 protected:
  explicit client_heartbeat_response(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  client_heartbeat_response(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const client_heartbeat_response& from);
  client_heartbeat_response(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, client_heartbeat_response&& from) noexcept
      : client_heartbeat_response(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kServerTimeFieldNumber = 1,
  };
  // int64 server_time = 1;
  void clear_server_time() ;
  ::int64_t server_time() const;
  void set_server_time(::int64_t value);

  private:
  ::int64_t _internal_server_time() const;
  void _internal_set_server_time(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:celeritas.proto.client.client_heartbeat_response)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const client_heartbeat_response& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int64_t server_time_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fclient_2fplayer_2fheartbeat_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull client_heartbeat_response_class_data_;
// -------------------------------------------------------------------

class client_heartbeat_request final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:celeritas.proto.client.client_heartbeat_request) */ {
 public:
  inline client_heartbeat_request() : client_heartbeat_request(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(client_heartbeat_request* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(client_heartbeat_request));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR client_heartbeat_request(::google::protobuf::internal::ConstantInitialized);

  inline client_heartbeat_request(const client_heartbeat_request& from) : client_heartbeat_request(nullptr, from) {}
  inline client_heartbeat_request(client_heartbeat_request&& from) noexcept
      : client_heartbeat_request(nullptr, ::std::move(from)) {}
  inline client_heartbeat_request& operator=(const client_heartbeat_request& from) {
    CopyFrom(from);
    return *this;
  }
  inline client_heartbeat_request& operator=(client_heartbeat_request&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const client_heartbeat_request& default_instance() {
    return *reinterpret_cast<const client_heartbeat_request*>(
        &_client_heartbeat_request_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(client_heartbeat_request& a, client_heartbeat_request& b) { a.Swap(&b); }
  inline void Swap(client_heartbeat_request* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(client_heartbeat_request* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  client_heartbeat_request* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<client_heartbeat_request>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const client_heartbeat_request& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const client_heartbeat_request& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "celeritas.proto.client.client_heartbeat_request"; }

 protected:
  explicit client_heartbeat_request(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  client_heartbeat_request(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const client_heartbeat_request& from);
  client_heartbeat_request(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, client_heartbeat_request&& from) noexcept
      : client_heartbeat_request(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:celeritas.proto.client.client_heartbeat_request)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 0,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  friend struct ::TableStruct_proto_2fclient_2fplayer_2fheartbeat_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull client_heartbeat_request_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// client_heartbeat_request

// -------------------------------------------------------------------

// client_heartbeat_response

// int64 server_time = 1;
inline void client_heartbeat_response::clear_server_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.server_time_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline ::int64_t client_heartbeat_response::server_time() const {
  // @@protoc_insertion_point(field_get:celeritas.proto.client.client_heartbeat_response.server_time)
  return _internal_server_time();
}
inline void client_heartbeat_response::set_server_time(::int64_t value) {
  _internal_set_server_time(value);
  _impl_._has_bits_[0] |= 0x00000001U;
  // @@protoc_insertion_point(field_set:celeritas.proto.client.client_heartbeat_response.server_time)
}
inline ::int64_t client_heartbeat_response::_internal_server_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.server_time_;
}
inline void client_heartbeat_response::_internal_set_server_time(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.server_time_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace client
}  // namespace proto
}  // namespace celeritas


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // proto_2fclient_2fplayer_2fheartbeat_2eproto_2epb_2eh
