// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/client/player/login.proto
// Protobuf C++ Version: 6.32.1

#ifndef proto_2fclient_2fplayer_2flogin_2eproto_2epb_2eh
#define proto_2fclient_2fplayer_2flogin_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6032001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_proto_2fclient_2fplayer_2flogin_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2fclient_2fplayer_2flogin_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_proto_2fclient_2fplayer_2flogin_2eproto;
}  // extern "C"
namespace celeritas {
namespace proto {
namespace client {
class client_login_request;
struct client_login_requestDefaultTypeInternal;
extern client_login_requestDefaultTypeInternal _client_login_request_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull client_login_request_class_data_;
class client_login_response;
struct client_login_responseDefaultTypeInternal;
extern client_login_responseDefaultTypeInternal _client_login_response_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull client_login_response_class_data_;
class login_request;
struct login_requestDefaultTypeInternal;
extern login_requestDefaultTypeInternal _login_request_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull login_request_class_data_;
class login_response;
struct login_responseDefaultTypeInternal;
extern login_responseDefaultTypeInternal _login_response_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull login_response_class_data_;
}  // namespace client
}  // namespace proto
}  // namespace celeritas
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace celeritas {
namespace proto {
namespace client {

// ===================================================================


// -------------------------------------------------------------------

class login_response final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:celeritas.proto.client.login_response) */ {
 public:
  inline login_response() : login_response(nullptr) {}
  ~login_response() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(login_response* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(login_response));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR login_response(::google::protobuf::internal::ConstantInitialized);

  inline login_response(const login_response& from) : login_response(nullptr, from) {}
  inline login_response(login_response&& from) noexcept
      : login_response(nullptr, ::std::move(from)) {}
  inline login_response& operator=(const login_response& from) {
    CopyFrom(from);
    return *this;
  }
  inline login_response& operator=(login_response&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const login_response& default_instance() {
    return *reinterpret_cast<const login_response*>(
        &_login_response_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(login_response& a, login_response& b) { a.Swap(&b); }
  inline void Swap(login_response* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(login_response* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  login_response* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<login_response>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const login_response& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const login_response& from) { login_response::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(login_response* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "celeritas.proto.client.login_response"; }

 protected:
  explicit login_response(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  login_response(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const login_response& from);
  login_response(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, login_response&& from) noexcept
      : login_response(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSessionKeyFieldNumber = 1,
    kCharacterIdFieldNumber = 2,
    kCurrentTimeFieldNumber = 3,
  };
  // string session_key = 1;
  void clear_session_key() ;
  const ::std::string& session_key() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_session_key(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_session_key();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_session_key();
  void set_allocated_session_key(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_session_key() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_session_key(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_session_key();

  public:
  // int64 character_id = 2;
  void clear_character_id() ;
  ::int64_t character_id() const;
  void set_character_id(::int64_t value);

  private:
  ::int64_t _internal_character_id() const;
  void _internal_set_character_id(::int64_t value);

  public:
  // int64 current_time = 3;
  void clear_current_time() ;
  ::int64_t current_time() const;
  void set_current_time(::int64_t value);

  private:
  ::int64_t _internal_current_time() const;
  void _internal_set_current_time(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:celeritas.proto.client.login_response)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 57,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const login_response& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr session_key_;
    ::int64_t character_id_;
    ::int64_t current_time_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fclient_2fplayer_2flogin_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull login_response_class_data_;
// -------------------------------------------------------------------

class login_request final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:celeritas.proto.client.login_request) */ {
 public:
  inline login_request() : login_request(nullptr) {}
  ~login_request() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(login_request* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(login_request));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR login_request(::google::protobuf::internal::ConstantInitialized);

  inline login_request(const login_request& from) : login_request(nullptr, from) {}
  inline login_request(login_request&& from) noexcept
      : login_request(nullptr, ::std::move(from)) {}
  inline login_request& operator=(const login_request& from) {
    CopyFrom(from);
    return *this;
  }
  inline login_request& operator=(login_request&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const login_request& default_instance() {
    return *reinterpret_cast<const login_request*>(
        &_login_request_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(login_request& a, login_request& b) { a.Swap(&b); }
  inline void Swap(login_request* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(login_request* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  login_request* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<login_request>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const login_request& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const login_request& from) { login_request::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(login_request* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "celeritas.proto.client.login_request"; }

 protected:
  explicit login_request(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  login_request(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const login_request& from);
  login_request(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, login_request&& from) noexcept
      : login_request(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTokenFieldNumber = 1,
    kGameServerIdFieldNumber = 2,
    kDeviceIdFieldNumber = 3,
    kAppVersionFieldNumber = 4,
  };
  // string token = 1;
  void clear_token() ;
  const ::std::string& token() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_token(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_token();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_token();
  void set_allocated_token(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_token() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_token(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_token();

  public:
  // string game_server_id = 2;
  void clear_game_server_id() ;
  const ::std::string& game_server_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_game_server_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_game_server_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_game_server_id();
  void set_allocated_game_server_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_game_server_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_game_server_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_game_server_id();

  public:
  // string device_id = 3;
  void clear_device_id() ;
  const ::std::string& device_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_device_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_device_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_device_id();
  void set_allocated_device_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_device_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_device_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_device_id();

  public:
  // string app_version = 4;
  void clear_app_version() ;
  const ::std::string& app_version() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_app_version(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_app_version();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_app_version();
  void set_allocated_app_version(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_app_version() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_app_version(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_app_version();

  public:
  // @@protoc_insertion_point(class_scope:celeritas.proto.client.login_request)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 84,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const login_request& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr token_;
    ::google::protobuf::internal::ArenaStringPtr game_server_id_;
    ::google::protobuf::internal::ArenaStringPtr device_id_;
    ::google::protobuf::internal::ArenaStringPtr app_version_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fclient_2fplayer_2flogin_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull login_request_class_data_;
// -------------------------------------------------------------------

class client_login_response final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:celeritas.proto.client.client_login_response) */ {
 public:
  inline client_login_response() : client_login_response(nullptr) {}
  ~client_login_response() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(client_login_response* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(client_login_response));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR client_login_response(::google::protobuf::internal::ConstantInitialized);

  inline client_login_response(const client_login_response& from) : client_login_response(nullptr, from) {}
  inline client_login_response(client_login_response&& from) noexcept
      : client_login_response(nullptr, ::std::move(from)) {}
  inline client_login_response& operator=(const client_login_response& from) {
    CopyFrom(from);
    return *this;
  }
  inline client_login_response& operator=(client_login_response&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const client_login_response& default_instance() {
    return *reinterpret_cast<const client_login_response*>(
        &_client_login_response_default_instance_);
  }
  enum PayloadCase {
    kLogin = 1,
    PAYLOAD_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(client_login_response& a, client_login_response& b) { a.Swap(&b); }
  inline void Swap(client_login_response* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(client_login_response* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  client_login_response* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<client_login_response>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const client_login_response& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const client_login_response& from) { client_login_response::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(client_login_response* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "celeritas.proto.client.client_login_response"; }

 protected:
  explicit client_login_response(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  client_login_response(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const client_login_response& from);
  client_login_response(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, client_login_response&& from) noexcept
      : client_login_response(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLoginFieldNumber = 1,
  };
  // .celeritas.proto.client.login_response login = 1;
  bool has_login() const;
  private:
  bool _internal_has_login() const;

  public:
  void clear_login() ;
  const ::celeritas::proto::client::login_response& login() const;
  [[nodiscard]] ::celeritas::proto::client::login_response* PROTOBUF_NULLABLE release_login();
  ::celeritas::proto::client::login_response* PROTOBUF_NONNULL mutable_login();
  void set_allocated_login(::celeritas::proto::client::login_response* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_login(::celeritas::proto::client::login_response* PROTOBUF_NULLABLE value);
  ::celeritas::proto::client::login_response* PROTOBUF_NULLABLE unsafe_arena_release_login();

  private:
  const ::celeritas::proto::client::login_response& _internal_login() const;
  ::celeritas::proto::client::login_response* PROTOBUF_NONNULL _internal_mutable_login();

  public:
  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:celeritas.proto.client.client_login_response)
 private:
  class _Internal;
  void set_has_login();
  inline bool has_payload() const;
  inline void clear_has_payload();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const client_login_response& from_msg);
    union PayloadUnion {
      constexpr PayloadUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::celeritas::proto::client::login_response* PROTOBUF_NULLABLE login_;
    } payload_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fclient_2fplayer_2flogin_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull client_login_response_class_data_;
// -------------------------------------------------------------------

class client_login_request final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:celeritas.proto.client.client_login_request) */ {
 public:
  inline client_login_request() : client_login_request(nullptr) {}
  ~client_login_request() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(client_login_request* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(client_login_request));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR client_login_request(::google::protobuf::internal::ConstantInitialized);

  inline client_login_request(const client_login_request& from) : client_login_request(nullptr, from) {}
  inline client_login_request(client_login_request&& from) noexcept
      : client_login_request(nullptr, ::std::move(from)) {}
  inline client_login_request& operator=(const client_login_request& from) {
    CopyFrom(from);
    return *this;
  }
  inline client_login_request& operator=(client_login_request&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const client_login_request& default_instance() {
    return *reinterpret_cast<const client_login_request*>(
        &_client_login_request_default_instance_);
  }
  enum PayloadCase {
    kLogin = 1,
    PAYLOAD_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(client_login_request& a, client_login_request& b) { a.Swap(&b); }
  inline void Swap(client_login_request* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(client_login_request* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  client_login_request* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<client_login_request>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const client_login_request& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const client_login_request& from) { client_login_request::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(client_login_request* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "celeritas.proto.client.client_login_request"; }

 protected:
  explicit client_login_request(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  client_login_request(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const client_login_request& from);
  client_login_request(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, client_login_request&& from) noexcept
      : client_login_request(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLoginFieldNumber = 1,
  };
  // .celeritas.proto.client.login_request login = 1;
  bool has_login() const;
  private:
  bool _internal_has_login() const;

  public:
  void clear_login() ;
  const ::celeritas::proto::client::login_request& login() const;
  [[nodiscard]] ::celeritas::proto::client::login_request* PROTOBUF_NULLABLE release_login();
  ::celeritas::proto::client::login_request* PROTOBUF_NONNULL mutable_login();
  void set_allocated_login(::celeritas::proto::client::login_request* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_login(::celeritas::proto::client::login_request* PROTOBUF_NULLABLE value);
  ::celeritas::proto::client::login_request* PROTOBUF_NULLABLE unsafe_arena_release_login();

  private:
  const ::celeritas::proto::client::login_request& _internal_login() const;
  ::celeritas::proto::client::login_request* PROTOBUF_NONNULL _internal_mutable_login();

  public:
  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:celeritas.proto.client.client_login_request)
 private:
  class _Internal;
  void set_has_login();
  inline bool has_payload() const;
  inline void clear_has_payload();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const client_login_request& from_msg);
    union PayloadUnion {
      constexpr PayloadUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::celeritas::proto::client::login_request* PROTOBUF_NULLABLE login_;
    } payload_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fclient_2fplayer_2flogin_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull client_login_request_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// login_request

// string token = 1;
inline void login_request::clear_token() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.token_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline const ::std::string& login_request::token() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:celeritas.proto.client.login_request.token)
  return _internal_token();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void login_request::set_token(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.token_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:celeritas.proto.client.login_request.token)
}
inline ::std::string* PROTOBUF_NONNULL login_request::mutable_token()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_token();
  // @@protoc_insertion_point(field_mutable:celeritas.proto.client.login_request.token)
  return _s;
}
inline const ::std::string& login_request::_internal_token() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.token_.Get();
}
inline void login_request::_internal_set_token(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.token_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL login_request::_internal_mutable_token() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  return _impl_.token_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE login_request::release_token() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:celeritas.proto.client.login_request.token)
  if ((_impl_._has_bits_[0] & 0x00000001U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001U;
  auto* released = _impl_.token_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.token_.Set("", GetArena());
  }
  return released;
}
inline void login_request::set_allocated_token(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  _impl_.token_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.token_.IsDefault()) {
    _impl_.token_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:celeritas.proto.client.login_request.token)
}

// string game_server_id = 2;
inline void login_request::clear_game_server_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.game_server_id_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline const ::std::string& login_request::game_server_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:celeritas.proto.client.login_request.game_server_id)
  return _internal_game_server_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void login_request::set_game_server_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002U;
  _impl_.game_server_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:celeritas.proto.client.login_request.game_server_id)
}
inline ::std::string* PROTOBUF_NONNULL login_request::mutable_game_server_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_game_server_id();
  // @@protoc_insertion_point(field_mutable:celeritas.proto.client.login_request.game_server_id)
  return _s;
}
inline const ::std::string& login_request::_internal_game_server_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.game_server_id_.Get();
}
inline void login_request::_internal_set_game_server_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002U;
  _impl_.game_server_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL login_request::_internal_mutable_game_server_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002U;
  return _impl_.game_server_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE login_request::release_game_server_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:celeritas.proto.client.login_request.game_server_id)
  if ((_impl_._has_bits_[0] & 0x00000002U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002U;
  auto* released = _impl_.game_server_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.game_server_id_.Set("", GetArena());
  }
  return released;
}
inline void login_request::set_allocated_game_server_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002U;
  }
  _impl_.game_server_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.game_server_id_.IsDefault()) {
    _impl_.game_server_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:celeritas.proto.client.login_request.game_server_id)
}

// string device_id = 3;
inline void login_request::clear_device_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.device_id_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004U;
}
inline const ::std::string& login_request::device_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:celeritas.proto.client.login_request.device_id)
  return _internal_device_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void login_request::set_device_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004U;
  _impl_.device_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:celeritas.proto.client.login_request.device_id)
}
inline ::std::string* PROTOBUF_NONNULL login_request::mutable_device_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_device_id();
  // @@protoc_insertion_point(field_mutable:celeritas.proto.client.login_request.device_id)
  return _s;
}
inline const ::std::string& login_request::_internal_device_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.device_id_.Get();
}
inline void login_request::_internal_set_device_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004U;
  _impl_.device_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL login_request::_internal_mutable_device_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004U;
  return _impl_.device_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE login_request::release_device_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:celeritas.proto.client.login_request.device_id)
  if ((_impl_._has_bits_[0] & 0x00000004U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004U;
  auto* released = _impl_.device_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.device_id_.Set("", GetArena());
  }
  return released;
}
inline void login_request::set_allocated_device_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004U;
  }
  _impl_.device_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.device_id_.IsDefault()) {
    _impl_.device_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:celeritas.proto.client.login_request.device_id)
}

// string app_version = 4;
inline void login_request::clear_app_version() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.app_version_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000008U;
}
inline const ::std::string& login_request::app_version() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:celeritas.proto.client.login_request.app_version)
  return _internal_app_version();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void login_request::set_app_version(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000008U;
  _impl_.app_version_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:celeritas.proto.client.login_request.app_version)
}
inline ::std::string* PROTOBUF_NONNULL login_request::mutable_app_version()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_app_version();
  // @@protoc_insertion_point(field_mutable:celeritas.proto.client.login_request.app_version)
  return _s;
}
inline const ::std::string& login_request::_internal_app_version() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.app_version_.Get();
}
inline void login_request::_internal_set_app_version(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000008U;
  _impl_.app_version_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL login_request::_internal_mutable_app_version() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000008U;
  return _impl_.app_version_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE login_request::release_app_version() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:celeritas.proto.client.login_request.app_version)
  if ((_impl_._has_bits_[0] & 0x00000008U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000008U;
  auto* released = _impl_.app_version_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.app_version_.Set("", GetArena());
  }
  return released;
}
inline void login_request::set_allocated_app_version(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008U;
  }
  _impl_.app_version_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.app_version_.IsDefault()) {
    _impl_.app_version_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:celeritas.proto.client.login_request.app_version)
}

// -------------------------------------------------------------------

// login_response

// string session_key = 1;
inline void login_response::clear_session_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.session_key_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline const ::std::string& login_response::session_key() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:celeritas.proto.client.login_response.session_key)
  return _internal_session_key();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void login_response::set_session_key(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.session_key_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:celeritas.proto.client.login_response.session_key)
}
inline ::std::string* PROTOBUF_NONNULL login_response::mutable_session_key()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_session_key();
  // @@protoc_insertion_point(field_mutable:celeritas.proto.client.login_response.session_key)
  return _s;
}
inline const ::std::string& login_response::_internal_session_key() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.session_key_.Get();
}
inline void login_response::_internal_set_session_key(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.session_key_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL login_response::_internal_mutable_session_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  return _impl_.session_key_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE login_response::release_session_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:celeritas.proto.client.login_response.session_key)
  if ((_impl_._has_bits_[0] & 0x00000001U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001U;
  auto* released = _impl_.session_key_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.session_key_.Set("", GetArena());
  }
  return released;
}
inline void login_response::set_allocated_session_key(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  _impl_.session_key_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.session_key_.IsDefault()) {
    _impl_.session_key_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:celeritas.proto.client.login_response.session_key)
}

// int64 character_id = 2;
inline void login_response::clear_character_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.character_id_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline ::int64_t login_response::character_id() const {
  // @@protoc_insertion_point(field_get:celeritas.proto.client.login_response.character_id)
  return _internal_character_id();
}
inline void login_response::set_character_id(::int64_t value) {
  _internal_set_character_id(value);
  _impl_._has_bits_[0] |= 0x00000002U;
  // @@protoc_insertion_point(field_set:celeritas.proto.client.login_response.character_id)
}
inline ::int64_t login_response::_internal_character_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.character_id_;
}
inline void login_response::_internal_set_character_id(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.character_id_ = value;
}

// int64 current_time = 3;
inline void login_response::clear_current_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.current_time_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000004U;
}
inline ::int64_t login_response::current_time() const {
  // @@protoc_insertion_point(field_get:celeritas.proto.client.login_response.current_time)
  return _internal_current_time();
}
inline void login_response::set_current_time(::int64_t value) {
  _internal_set_current_time(value);
  _impl_._has_bits_[0] |= 0x00000004U;
  // @@protoc_insertion_point(field_set:celeritas.proto.client.login_response.current_time)
}
inline ::int64_t login_response::_internal_current_time() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.current_time_;
}
inline void login_response::_internal_set_current_time(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.current_time_ = value;
}

// -------------------------------------------------------------------

// client_login_request

// .celeritas.proto.client.login_request login = 1;
inline bool client_login_request::has_login() const {
  return payload_case() == kLogin;
}
inline bool client_login_request::_internal_has_login() const {
  return payload_case() == kLogin;
}
inline void client_login_request::set_has_login() {
  _impl_._oneof_case_[0] = kLogin;
}
inline void client_login_request::clear_login() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kLogin) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.login_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.login_);
    }
    clear_has_payload();
  }
}
inline ::celeritas::proto::client::login_request* PROTOBUF_NULLABLE client_login_request::release_login() {
  // @@protoc_insertion_point(field_release:celeritas.proto.client.client_login_request.login)
  if (payload_case() == kLogin) {
    clear_has_payload();
    auto* temp = _impl_.payload_.login_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.login_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::celeritas::proto::client::login_request& client_login_request::_internal_login() const {
  return payload_case() == kLogin ? *_impl_.payload_.login_ : reinterpret_cast<::celeritas::proto::client::login_request&>(::celeritas::proto::client::_login_request_default_instance_);
}
inline const ::celeritas::proto::client::login_request& client_login_request::login() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:celeritas.proto.client.client_login_request.login)
  return _internal_login();
}
inline ::celeritas::proto::client::login_request* PROTOBUF_NULLABLE client_login_request::unsafe_arena_release_login() {
  // @@protoc_insertion_point(field_unsafe_arena_release:celeritas.proto.client.client_login_request.login)
  if (payload_case() == kLogin) {
    clear_has_payload();
    auto* temp = _impl_.payload_.login_;
    _impl_.payload_.login_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void client_login_request::unsafe_arena_set_allocated_login(
    ::celeritas::proto::client::login_request* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_login();
    _impl_.payload_.login_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:celeritas.proto.client.client_login_request.login)
}
inline ::celeritas::proto::client::login_request* PROTOBUF_NONNULL client_login_request::_internal_mutable_login() {
  if (payload_case() != kLogin) {
    clear_payload();
    set_has_login();
    _impl_.payload_.login_ = 
        ::google::protobuf::Message::DefaultConstruct<::celeritas::proto::client::login_request>(GetArena());
  }
  return _impl_.payload_.login_;
}
inline ::celeritas::proto::client::login_request* PROTOBUF_NONNULL client_login_request::mutable_login()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::celeritas::proto::client::login_request* _msg = _internal_mutable_login();
  // @@protoc_insertion_point(field_mutable:celeritas.proto.client.client_login_request.login)
  return _msg;
}

inline bool client_login_request::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void client_login_request::clear_has_payload() {
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline client_login_request::PayloadCase client_login_request::payload_case() const {
  return client_login_request::PayloadCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// client_login_response

// .celeritas.proto.client.login_response login = 1;
inline bool client_login_response::has_login() const {
  return payload_case() == kLogin;
}
inline bool client_login_response::_internal_has_login() const {
  return payload_case() == kLogin;
}
inline void client_login_response::set_has_login() {
  _impl_._oneof_case_[0] = kLogin;
}
inline void client_login_response::clear_login() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (payload_case() == kLogin) {
    if (GetArena() == nullptr) {
      delete _impl_.payload_.login_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.login_);
    }
    clear_has_payload();
  }
}
inline ::celeritas::proto::client::login_response* PROTOBUF_NULLABLE client_login_response::release_login() {
  // @@protoc_insertion_point(field_release:celeritas.proto.client.client_login_response.login)
  if (payload_case() == kLogin) {
    clear_has_payload();
    auto* temp = _impl_.payload_.login_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.login_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::celeritas::proto::client::login_response& client_login_response::_internal_login() const {
  return payload_case() == kLogin ? *_impl_.payload_.login_ : reinterpret_cast<::celeritas::proto::client::login_response&>(::celeritas::proto::client::_login_response_default_instance_);
}
inline const ::celeritas::proto::client::login_response& client_login_response::login() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:celeritas.proto.client.client_login_response.login)
  return _internal_login();
}
inline ::celeritas::proto::client::login_response* PROTOBUF_NULLABLE client_login_response::unsafe_arena_release_login() {
  // @@protoc_insertion_point(field_unsafe_arena_release:celeritas.proto.client.client_login_response.login)
  if (payload_case() == kLogin) {
    clear_has_payload();
    auto* temp = _impl_.payload_.login_;
    _impl_.payload_.login_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void client_login_response::unsafe_arena_set_allocated_login(
    ::celeritas::proto::client::login_response* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_login();
    _impl_.payload_.login_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:celeritas.proto.client.client_login_response.login)
}
inline ::celeritas::proto::client::login_response* PROTOBUF_NONNULL client_login_response::_internal_mutable_login() {
  if (payload_case() != kLogin) {
    clear_payload();
    set_has_login();
    _impl_.payload_.login_ = 
        ::google::protobuf::Message::DefaultConstruct<::celeritas::proto::client::login_response>(GetArena());
  }
  return _impl_.payload_.login_;
}
inline ::celeritas::proto::client::login_response* PROTOBUF_NONNULL client_login_response::mutable_login()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::celeritas::proto::client::login_response* _msg = _internal_mutable_login();
  // @@protoc_insertion_point(field_mutable:celeritas.proto.client.client_login_response.login)
  return _msg;
}

inline bool client_login_response::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void client_login_response::clear_has_payload() {
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline client_login_response::PayloadCase client_login_response::payload_case() const {
  return client_login_response::PayloadCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace client
}  // namespace proto
}  // namespace celeritas


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // proto_2fclient_2fplayer_2flogin_2eproto_2epb_2eh
