// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/client/player/player.proto
// Protobuf C++ Version: 6.32.1

#ifndef proto_2fclient_2fplayer_2fplayer_2eproto_2epb_2eh
#define proto_2fclient_2fplayer_2fplayer_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6032001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "proto/client/player/login.pb.h"
#include "proto/client/player/heartbeat.pb.h"
#include "proto/client/player/role.pb.h"
#include "proto/client/player/debug.pb.h"
#include "proto/client/player/red_dot.pb.h"
#include "proto/client/player/item.pb.h"
#include "proto/client/player/develop.pb.h"
#include "proto/client/player/mail.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_proto_2fclient_2fplayer_2fplayer_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2fclient_2fplayer_2fplayer_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_proto_2fclient_2fplayer_2fplayer_2eproto;
}  // extern "C"
namespace celeritas {
namespace proto {
namespace client {
class client_player_request;
struct client_player_requestDefaultTypeInternal;
extern client_player_requestDefaultTypeInternal _client_player_request_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull client_player_request_class_data_;
class client_player_response;
struct client_player_responseDefaultTypeInternal;
extern client_player_responseDefaultTypeInternal _client_player_response_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull client_player_response_class_data_;
}  // namespace client
}  // namespace proto
}  // namespace celeritas
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace celeritas {
namespace proto {
namespace client {

// ===================================================================


// -------------------------------------------------------------------

class client_player_request final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:celeritas.proto.client.client_player_request) */ {
 public:
  inline client_player_request() : client_player_request(nullptr) {}
  ~client_player_request() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(client_player_request* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(client_player_request));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR client_player_request(::google::protobuf::internal::ConstantInitialized);

  inline client_player_request(const client_player_request& from) : client_player_request(nullptr, from) {}
  inline client_player_request(client_player_request&& from) noexcept
      : client_player_request(nullptr, ::std::move(from)) {}
  inline client_player_request& operator=(const client_player_request& from) {
    CopyFrom(from);
    return *this;
  }
  inline client_player_request& operator=(client_player_request&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const client_player_request& default_instance() {
    return *reinterpret_cast<const client_player_request*>(
        &_client_player_request_default_instance_);
  }
  enum PayloadCase {
    kLogin = 1,
    kHeartbeat = 2,
    kDebug = 3,
    kRole = 4,
    kRedDot = 5,
    kItem = 6,
    kDevelop = 7,
    kMail = 8,
    PAYLOAD_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(client_player_request& a, client_player_request& b) { a.Swap(&b); }
  inline void Swap(client_player_request* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(client_player_request* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  client_player_request* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<client_player_request>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const client_player_request& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const client_player_request& from) { client_player_request::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(client_player_request* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "celeritas.proto.client.client_player_request"; }

 protected:
  explicit client_player_request(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  client_player_request(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const client_player_request& from);
  client_player_request(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, client_player_request&& from) noexcept
      : client_player_request(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLoginFieldNumber = 1,
    kHeartbeatFieldNumber = 2,
    kDebugFieldNumber = 3,
    kRoleFieldNumber = 4,
    kRedDotFieldNumber = 5,
    kItemFieldNumber = 6,
    kDevelopFieldNumber = 7,
    kMailFieldNumber = 8,
  };
  // .celeritas.proto.client.client_login_request login = 1;
  bool has_login() const;
  private:
  bool _internal_has_login() const;

  public:
  void clear_login() ;
  const ::celeritas::proto::client::client_login_request& login() const;
  [[nodiscard]] ::celeritas::proto::client::client_login_request* PROTOBUF_NULLABLE release_login();
  ::celeritas::proto::client::client_login_request* PROTOBUF_NONNULL mutable_login();
  void set_allocated_login(::celeritas::proto::client::client_login_request* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_login(::celeritas::proto::client::client_login_request* PROTOBUF_NULLABLE value);
  ::celeritas::proto::client::client_login_request* PROTOBUF_NULLABLE unsafe_arena_release_login();

  private:
  const ::celeritas::proto::client::client_login_request& _internal_login() const;
  ::celeritas::proto::client::client_login_request* PROTOBUF_NONNULL _internal_mutable_login();

  public:
  // .celeritas.proto.client.client_heartbeat_request heartbeat = 2;
  bool has_heartbeat() const;
  private:
  bool _internal_has_heartbeat() const;

  public:
  void clear_heartbeat() ;
  const ::celeritas::proto::client::client_heartbeat_request& heartbeat() const;
  [[nodiscard]] ::celeritas::proto::client::client_heartbeat_request* PROTOBUF_NULLABLE release_heartbeat();
  ::celeritas::proto::client::client_heartbeat_request* PROTOBUF_NONNULL mutable_heartbeat();
  void set_allocated_heartbeat(::celeritas::proto::client::client_heartbeat_request* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_heartbeat(::celeritas::proto::client::client_heartbeat_request* PROTOBUF_NULLABLE value);
  ::celeritas::proto::client::client_heartbeat_request* PROTOBUF_NULLABLE unsafe_arena_release_heartbeat();

  private:
  const ::celeritas::proto::client::client_heartbeat_request& _internal_heartbeat() const;
  ::celeritas::proto::client::client_heartbeat_request* PROTOBUF_NONNULL _internal_mutable_heartbeat();

  public:
  // .celeritas.proto.client.client_debug_request debug = 3;
  bool has_debug() const;
  private:
  bool _internal_has_debug() const;

  public:
  void clear_debug() ;
  const ::celeritas::proto::client::client_debug_request& debug() const;
  [[nodiscard]] ::celeritas::proto::client::client_debug_request* PROTOBUF_NULLABLE release_debug();
  ::celeritas::proto::client::client_debug_request* PROTOBUF_NONNULL mutable_debug();
  void set_allocated_debug(::celeritas::proto::client::client_debug_request* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_debug(::celeritas::proto::client::client_debug_request* PROTOBUF_NULLABLE value);
  ::celeritas::proto::client::client_debug_request* PROTOBUF_NULLABLE unsafe_arena_release_debug();

  private:
  const ::celeritas::proto::client::client_debug_request& _internal_debug() const;
  ::celeritas::proto::client::client_debug_request* PROTOBUF_NONNULL _internal_mutable_debug();

  public:
  // .celeritas.proto.client.client_role_request role = 4;
  bool has_role() const;
  private:
  bool _internal_has_role() const;

  public:
  void clear_role() ;
  const ::celeritas::proto::client::client_role_request& role() const;
  [[nodiscard]] ::celeritas::proto::client::client_role_request* PROTOBUF_NULLABLE release_role();
  ::celeritas::proto::client::client_role_request* PROTOBUF_NONNULL mutable_role();
  void set_allocated_role(::celeritas::proto::client::client_role_request* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_role(::celeritas::proto::client::client_role_request* PROTOBUF_NULLABLE value);
  ::celeritas::proto::client::client_role_request* PROTOBUF_NULLABLE unsafe_arena_release_role();

  private:
  const ::celeritas::proto::client::client_role_request& _internal_role() const;
  ::celeritas::proto::client::client_role_request* PROTOBUF_NONNULL _internal_mutable_role();

  public:
  // .celeritas.proto.client.client_red_dot_request red_dot = 5;
  bool has_red_dot() const;
  private:
  bool _internal_has_red_dot() const;

  public:
  void clear_red_dot() ;
  const ::celeritas::proto::client::client_red_dot_request& red_dot() const;
  [[nodiscard]] ::celeritas::proto::client::client_red_dot_request* PROTOBUF_NULLABLE release_red_dot();
  ::celeritas::proto::client::client_red_dot_request* PROTOBUF_NONNULL mutable_red_dot();
  void set_allocated_red_dot(::celeritas::proto::client::client_red_dot_request* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_red_dot(::celeritas::proto::client::client_red_dot_request* PROTOBUF_NULLABLE value);
  ::celeritas::proto::client::client_red_dot_request* PROTOBUF_NULLABLE unsafe_arena_release_red_dot();

  private:
  const ::celeritas::proto::client::client_red_dot_request& _internal_red_dot() const;
  ::celeritas::proto::client::client_red_dot_request* PROTOBUF_NONNULL _internal_mutable_red_dot();

  public:
  // .celeritas.proto.client.client_item_request item = 6;
  bool has_item() const;
  private:
  bool _internal_has_item() const;

  public:
  void clear_item() ;
  const ::celeritas::proto::client::client_item_request& item() const;
  [[nodiscard]] ::celeritas::proto::client::client_item_request* PROTOBUF_NULLABLE release_item();
  ::celeritas::proto::client::client_item_request* PROTOBUF_NONNULL mutable_item();
  void set_allocated_item(::celeritas::proto::client::client_item_request* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_item(::celeritas::proto::client::client_item_request* PROTOBUF_NULLABLE value);
  ::celeritas::proto::client::client_item_request* PROTOBUF_NULLABLE unsafe_arena_release_item();

  private:
  const ::celeritas::proto::client::client_item_request& _internal_item() const;
  ::celeritas::proto::client::client_item_request* PROTOBUF_NONNULL _internal_mutable_item();

  public:
  // .celeritas.proto.client.client_develop_request develop = 7;
  bool has_develop() const;
  private:
  bool _internal_has_develop() const;

  public:
  void clear_develop() ;
  const ::celeritas::proto::client::client_develop_request& develop() const;
  [[nodiscard]] ::celeritas::proto::client::client_develop_request* PROTOBUF_NULLABLE release_develop();
  ::celeritas::proto::client::client_develop_request* PROTOBUF_NONNULL mutable_develop();
  void set_allocated_develop(::celeritas::proto::client::client_develop_request* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_develop(::celeritas::proto::client::client_develop_request* PROTOBUF_NULLABLE value);
  ::celeritas::proto::client::client_develop_request* PROTOBUF_NULLABLE unsafe_arena_release_develop();

  private:
  const ::celeritas::proto::client::client_develop_request& _internal_develop() const;
  ::celeritas::proto::client::client_develop_request* PROTOBUF_NONNULL _internal_mutable_develop();

  public:
  // .celeritas.proto.client.client_mail_request mail = 8;
  bool has_mail() const;
  private:
  bool _internal_has_mail() const;

  public:
  void clear_mail() ;
  const ::celeritas::proto::client::client_mail_request& mail() const;
  [[nodiscard]] ::celeritas::proto::client::client_mail_request* PROTOBUF_NULLABLE release_mail();
  ::celeritas::proto::client::client_mail_request* PROTOBUF_NONNULL mutable_mail();
  void set_allocated_mail(::celeritas::proto::client::client_mail_request* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_mail(::celeritas::proto::client::client_mail_request* PROTOBUF_NULLABLE value);
  ::celeritas::proto::client::client_mail_request* PROTOBUF_NULLABLE unsafe_arena_release_mail();

  private:
  const ::celeritas::proto::client::client_mail_request& _internal_mail() const;
  ::celeritas::proto::client::client_mail_request* PROTOBUF_NONNULL _internal_mutable_mail();

  public:
  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:celeritas.proto.client.client_player_request)
 private:
  class _Internal;
  void set_has_login();
  void set_has_heartbeat();
  void set_has_debug();
  void set_has_role();
  void set_has_red_dot();
  void set_has_item();
  void set_has_develop();
  void set_has_mail();
  inline bool has_payload() const;
  inline void clear_has_payload();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 8,
                                   8, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const client_player_request& from_msg);
    union PayloadUnion {
      constexpr PayloadUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE login_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE heartbeat_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE debug_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE role_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE red_dot_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE item_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE develop_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE mail_;
    } payload_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fclient_2fplayer_2fplayer_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull client_player_request_class_data_;
// -------------------------------------------------------------------

class client_player_response final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:celeritas.proto.client.client_player_response) */ {
 public:
  inline client_player_response() : client_player_response(nullptr) {}
  ~client_player_response() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(client_player_response* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(client_player_response));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR client_player_response(::google::protobuf::internal::ConstantInitialized);

  inline client_player_response(const client_player_response& from) : client_player_response(nullptr, from) {}
  inline client_player_response(client_player_response&& from) noexcept
      : client_player_response(nullptr, ::std::move(from)) {}
  inline client_player_response& operator=(const client_player_response& from) {
    CopyFrom(from);
    return *this;
  }
  inline client_player_response& operator=(client_player_response&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const client_player_response& default_instance() {
    return *reinterpret_cast<const client_player_response*>(
        &_client_player_response_default_instance_);
  }
  enum PayloadCase {
    kLogin = 1,
    kHeartbeat = 2,
    kDebug = 3,
    kRole = 4,
    kRedDot = 5,
    kItem = 6,
    kDevelop = 7,
    kMail = 8,
    PAYLOAD_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(client_player_response& a, client_player_response& b) { a.Swap(&b); }
  inline void Swap(client_player_response* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(client_player_response* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  client_player_response* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<client_player_response>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const client_player_response& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const client_player_response& from) { client_player_response::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(client_player_response* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "celeritas.proto.client.client_player_response"; }

 protected:
  explicit client_player_response(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  client_player_response(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const client_player_response& from);
  client_player_response(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, client_player_response&& from) noexcept
      : client_player_response(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLoginFieldNumber = 1,
    kHeartbeatFieldNumber = 2,
    kDebugFieldNumber = 3,
    kRoleFieldNumber = 4,
    kRedDotFieldNumber = 5,
    kItemFieldNumber = 6,
    kDevelopFieldNumber = 7,
    kMailFieldNumber = 8,
  };
  // .celeritas.proto.client.client_login_response login = 1;
  bool has_login() const;
  private:
  bool _internal_has_login() const;

  public:
  void clear_login() ;
  const ::celeritas::proto::client::client_login_response& login() const;
  [[nodiscard]] ::celeritas::proto::client::client_login_response* PROTOBUF_NULLABLE release_login();
  ::celeritas::proto::client::client_login_response* PROTOBUF_NONNULL mutable_login();
  void set_allocated_login(::celeritas::proto::client::client_login_response* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_login(::celeritas::proto::client::client_login_response* PROTOBUF_NULLABLE value);
  ::celeritas::proto::client::client_login_response* PROTOBUF_NULLABLE unsafe_arena_release_login();

  private:
  const ::celeritas::proto::client::client_login_response& _internal_login() const;
  ::celeritas::proto::client::client_login_response* PROTOBUF_NONNULL _internal_mutable_login();

  public:
  // .celeritas.proto.client.client_heartbeat_response heartbeat = 2;
  bool has_heartbeat() const;
  private:
  bool _internal_has_heartbeat() const;

  public:
  void clear_heartbeat() ;
  const ::celeritas::proto::client::client_heartbeat_response& heartbeat() const;
  [[nodiscard]] ::celeritas::proto::client::client_heartbeat_response* PROTOBUF_NULLABLE release_heartbeat();
  ::celeritas::proto::client::client_heartbeat_response* PROTOBUF_NONNULL mutable_heartbeat();
  void set_allocated_heartbeat(::celeritas::proto::client::client_heartbeat_response* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_heartbeat(::celeritas::proto::client::client_heartbeat_response* PROTOBUF_NULLABLE value);
  ::celeritas::proto::client::client_heartbeat_response* PROTOBUF_NULLABLE unsafe_arena_release_heartbeat();

  private:
  const ::celeritas::proto::client::client_heartbeat_response& _internal_heartbeat() const;
  ::celeritas::proto::client::client_heartbeat_response* PROTOBUF_NONNULL _internal_mutable_heartbeat();

  public:
  // .celeritas.proto.client.client_debug_response debug = 3;
  bool has_debug() const;
  private:
  bool _internal_has_debug() const;

  public:
  void clear_debug() ;
  const ::celeritas::proto::client::client_debug_response& debug() const;
  [[nodiscard]] ::celeritas::proto::client::client_debug_response* PROTOBUF_NULLABLE release_debug();
  ::celeritas::proto::client::client_debug_response* PROTOBUF_NONNULL mutable_debug();
  void set_allocated_debug(::celeritas::proto::client::client_debug_response* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_debug(::celeritas::proto::client::client_debug_response* PROTOBUF_NULLABLE value);
  ::celeritas::proto::client::client_debug_response* PROTOBUF_NULLABLE unsafe_arena_release_debug();

  private:
  const ::celeritas::proto::client::client_debug_response& _internal_debug() const;
  ::celeritas::proto::client::client_debug_response* PROTOBUF_NONNULL _internal_mutable_debug();

  public:
  // .celeritas.proto.client.client_role_response role = 4;
  bool has_role() const;
  private:
  bool _internal_has_role() const;

  public:
  void clear_role() ;
  const ::celeritas::proto::client::client_role_response& role() const;
  [[nodiscard]] ::celeritas::proto::client::client_role_response* PROTOBUF_NULLABLE release_role();
  ::celeritas::proto::client::client_role_response* PROTOBUF_NONNULL mutable_role();
  void set_allocated_role(::celeritas::proto::client::client_role_response* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_role(::celeritas::proto::client::client_role_response* PROTOBUF_NULLABLE value);
  ::celeritas::proto::client::client_role_response* PROTOBUF_NULLABLE unsafe_arena_release_role();

  private:
  const ::celeritas::proto::client::client_role_response& _internal_role() const;
  ::celeritas::proto::client::client_role_response* PROTOBUF_NONNULL _internal_mutable_role();

  public:
  // .celeritas.proto.client.client_red_dot_response red_dot = 5;
  bool has_red_dot() const;
  private:
  bool _internal_has_red_dot() const;

  public:
  void clear_red_dot() ;
  const ::celeritas::proto::client::client_red_dot_response& red_dot() const;
  [[nodiscard]] ::celeritas::proto::client::client_red_dot_response* PROTOBUF_NULLABLE release_red_dot();
  ::celeritas::proto::client::client_red_dot_response* PROTOBUF_NONNULL mutable_red_dot();
  void set_allocated_red_dot(::celeritas::proto::client::client_red_dot_response* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_red_dot(::celeritas::proto::client::client_red_dot_response* PROTOBUF_NULLABLE value);
  ::celeritas::proto::client::client_red_dot_response* PROTOBUF_NULLABLE unsafe_arena_release_red_dot();

  private:
  const ::celeritas::proto::client::client_red_dot_response& _internal_red_dot() const;
  ::celeritas::proto::client::client_red_dot_response* PROTOBUF_NONNULL _internal_mutable_red_dot();

  public:
  // .celeritas.proto.client.client_item_response item = 6;
  bool has_item() const;
  private:
  bool _internal_has_item() const;

  public:
  void clear_item() ;
  const ::celeritas::proto::client::client_item_response& item() const;
  [[nodiscard]] ::celeritas::proto::client::client_item_response* PROTOBUF_NULLABLE release_item();
  ::celeritas::proto::client::client_item_response* PROTOBUF_NONNULL mutable_item();
  void set_allocated_item(::celeritas::proto::client::client_item_response* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_item(::celeritas::proto::client::client_item_response* PROTOBUF_NULLABLE value);
  ::celeritas::proto::client::client_item_response* PROTOBUF_NULLABLE unsafe_arena_release_item();

  private:
  const ::celeritas::proto::client::client_item_response& _internal_item() const;
  ::celeritas::proto::client::client_item_response* PROTOBUF_NONNULL _internal_mutable_item();

  public:
  // .celeritas.proto.client.client_develop_response develop = 7;
  bool has_develop() const;
  private:
  bool _internal_has_develop() const;

  public:
  void clear_develop() ;
  const ::celeritas::proto::client::client_develop_response& develop() const;
  [[nodiscard]] ::celeritas::proto::client::client_develop_response* PROTOBUF_NULLABLE release_develop();
  ::celeritas::proto::client::client_develop_response* PROTOBUF_NONNULL mutable_develop();
  void set_allocated_develop(::celeritas::proto::client::client_develop_response* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_develop(::celeritas::proto::client::client_develop_response* PROTOBUF_NULLABLE value);
  ::celeritas::proto::client::client_develop_response* PROTOBUF_NULLABLE unsafe_arena_release_develop();

  private:
  const ::celeritas::proto::client::client_develop_response& _internal_develop() const;
  ::celeritas::proto::client::client_develop_response* PROTOBUF_NONNULL _internal_mutable_develop();

  public:
  // .celeritas.proto.client.client_mail_response mail = 8;
  bool has_mail() const;
  private:
  bool _internal_has_mail() const;

  public:
  void clear_mail() ;
  const ::celeritas::proto::client::client_mail_response& mail() const;
  [[nodiscard]] ::celeritas::proto::client::client_mail_response* PROTOBUF_NULLABLE release_mail();
  ::celeritas::proto::client::client_mail_response* PROTOBUF_NONNULL mutable_mail();
  void set_allocated_mail(::celeritas::proto::client::client_mail_response* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_mail(::celeritas::proto::client::client_mail_response* PROTOBUF_NULLABLE value);
  ::celeritas::proto::client::client_mail_response* PROTOBUF_NULLABLE unsafe_arena_release_mail();

  private:
  const ::celeritas::proto::client::client_mail_response& _internal_mail() const;
  ::celeritas::proto::client::client_mail_response* PROTOBUF_NONNULL _internal_mutable_mail();

  public:
  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:celeritas.proto.client.client_player_response)
 private:
  class _Internal;
  void set_has_login();
  void set_has_heartbeat();
  void set_has_debug();
  void set_has_role();
  void set_has_red_dot();
  void set_has_item();
  void set_has_develop();
  void set_has_mail();
  inline bool has_payload() const;
  inline void clear_has_payload();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 8,
                                   8, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const client_player_response& from_msg);
    union PayloadUnion {
      constexpr PayloadUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE login_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE heartbeat_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE debug_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE role_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE red_dot_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE item_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE develop_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE mail_;
    } payload_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fclient_2fplayer_2fplayer_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull client_player_response_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// client_player_request

// .celeritas.proto.client.client_login_request login = 1;
inline bool client_player_request::has_login() const {
  return payload_case() == kLogin;
}
inline bool client_player_request::_internal_has_login() const {
  return payload_case() == kLogin;
}
inline void client_player_request::set_has_login() {
  _impl_._oneof_case_[0] = kLogin;
}
inline ::celeritas::proto::client::client_login_request* PROTOBUF_NULLABLE client_player_request::release_login() {
  // @@protoc_insertion_point(field_release:celeritas.proto.client.client_player_request.login)
  if (payload_case() == kLogin) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::celeritas::proto::client::client_login_request*>(_impl_.payload_.login_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.login_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::celeritas::proto::client::client_login_request& client_player_request::_internal_login() const {
  return payload_case() == kLogin ? *reinterpret_cast<::celeritas::proto::client::client_login_request*>(_impl_.payload_.login_) : reinterpret_cast<::celeritas::proto::client::client_login_request&>(::celeritas::proto::client::_client_login_request_default_instance_);
}
inline const ::celeritas::proto::client::client_login_request& client_player_request::login() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:celeritas.proto.client.client_player_request.login)
  return _internal_login();
}
inline ::celeritas::proto::client::client_login_request* PROTOBUF_NULLABLE client_player_request::unsafe_arena_release_login() {
  // @@protoc_insertion_point(field_unsafe_arena_release:celeritas.proto.client.client_player_request.login)
  if (payload_case() == kLogin) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::celeritas::proto::client::client_login_request*>(_impl_.payload_.login_);
    _impl_.payload_.login_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void client_player_request::unsafe_arena_set_allocated_login(
    ::celeritas::proto::client::client_login_request* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_login();
    _impl_.payload_.login_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:celeritas.proto.client.client_player_request.login)
}
inline ::celeritas::proto::client::client_login_request* PROTOBUF_NONNULL client_player_request::_internal_mutable_login() {
  if (payload_case() != kLogin) {
    clear_payload();
    set_has_login();
    _impl_.payload_.login_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::celeritas::proto::client::client_login_request>(GetArena()));
  }
  return reinterpret_cast<::celeritas::proto::client::client_login_request*>(_impl_.payload_.login_);
}
inline ::celeritas::proto::client::client_login_request* PROTOBUF_NONNULL client_player_request::mutable_login()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::celeritas::proto::client::client_login_request* _msg = _internal_mutable_login();
  // @@protoc_insertion_point(field_mutable:celeritas.proto.client.client_player_request.login)
  return _msg;
}

// .celeritas.proto.client.client_heartbeat_request heartbeat = 2;
inline bool client_player_request::has_heartbeat() const {
  return payload_case() == kHeartbeat;
}
inline bool client_player_request::_internal_has_heartbeat() const {
  return payload_case() == kHeartbeat;
}
inline void client_player_request::set_has_heartbeat() {
  _impl_._oneof_case_[0] = kHeartbeat;
}
inline ::celeritas::proto::client::client_heartbeat_request* PROTOBUF_NULLABLE client_player_request::release_heartbeat() {
  // @@protoc_insertion_point(field_release:celeritas.proto.client.client_player_request.heartbeat)
  if (payload_case() == kHeartbeat) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::celeritas::proto::client::client_heartbeat_request*>(_impl_.payload_.heartbeat_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.heartbeat_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::celeritas::proto::client::client_heartbeat_request& client_player_request::_internal_heartbeat() const {
  return payload_case() == kHeartbeat ? *reinterpret_cast<::celeritas::proto::client::client_heartbeat_request*>(_impl_.payload_.heartbeat_) : reinterpret_cast<::celeritas::proto::client::client_heartbeat_request&>(::celeritas::proto::client::_client_heartbeat_request_default_instance_);
}
inline const ::celeritas::proto::client::client_heartbeat_request& client_player_request::heartbeat() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:celeritas.proto.client.client_player_request.heartbeat)
  return _internal_heartbeat();
}
inline ::celeritas::proto::client::client_heartbeat_request* PROTOBUF_NULLABLE client_player_request::unsafe_arena_release_heartbeat() {
  // @@protoc_insertion_point(field_unsafe_arena_release:celeritas.proto.client.client_player_request.heartbeat)
  if (payload_case() == kHeartbeat) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::celeritas::proto::client::client_heartbeat_request*>(_impl_.payload_.heartbeat_);
    _impl_.payload_.heartbeat_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void client_player_request::unsafe_arena_set_allocated_heartbeat(
    ::celeritas::proto::client::client_heartbeat_request* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_heartbeat();
    _impl_.payload_.heartbeat_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:celeritas.proto.client.client_player_request.heartbeat)
}
inline ::celeritas::proto::client::client_heartbeat_request* PROTOBUF_NONNULL client_player_request::_internal_mutable_heartbeat() {
  if (payload_case() != kHeartbeat) {
    clear_payload();
    set_has_heartbeat();
    _impl_.payload_.heartbeat_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::celeritas::proto::client::client_heartbeat_request>(GetArena()));
  }
  return reinterpret_cast<::celeritas::proto::client::client_heartbeat_request*>(_impl_.payload_.heartbeat_);
}
inline ::celeritas::proto::client::client_heartbeat_request* PROTOBUF_NONNULL client_player_request::mutable_heartbeat()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::celeritas::proto::client::client_heartbeat_request* _msg = _internal_mutable_heartbeat();
  // @@protoc_insertion_point(field_mutable:celeritas.proto.client.client_player_request.heartbeat)
  return _msg;
}

// .celeritas.proto.client.client_debug_request debug = 3;
inline bool client_player_request::has_debug() const {
  return payload_case() == kDebug;
}
inline bool client_player_request::_internal_has_debug() const {
  return payload_case() == kDebug;
}
inline void client_player_request::set_has_debug() {
  _impl_._oneof_case_[0] = kDebug;
}
inline ::celeritas::proto::client::client_debug_request* PROTOBUF_NULLABLE client_player_request::release_debug() {
  // @@protoc_insertion_point(field_release:celeritas.proto.client.client_player_request.debug)
  if (payload_case() == kDebug) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::celeritas::proto::client::client_debug_request*>(_impl_.payload_.debug_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.debug_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::celeritas::proto::client::client_debug_request& client_player_request::_internal_debug() const {
  return payload_case() == kDebug ? *reinterpret_cast<::celeritas::proto::client::client_debug_request*>(_impl_.payload_.debug_) : reinterpret_cast<::celeritas::proto::client::client_debug_request&>(::celeritas::proto::client::_client_debug_request_default_instance_);
}
inline const ::celeritas::proto::client::client_debug_request& client_player_request::debug() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:celeritas.proto.client.client_player_request.debug)
  return _internal_debug();
}
inline ::celeritas::proto::client::client_debug_request* PROTOBUF_NULLABLE client_player_request::unsafe_arena_release_debug() {
  // @@protoc_insertion_point(field_unsafe_arena_release:celeritas.proto.client.client_player_request.debug)
  if (payload_case() == kDebug) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::celeritas::proto::client::client_debug_request*>(_impl_.payload_.debug_);
    _impl_.payload_.debug_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void client_player_request::unsafe_arena_set_allocated_debug(
    ::celeritas::proto::client::client_debug_request* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_debug();
    _impl_.payload_.debug_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:celeritas.proto.client.client_player_request.debug)
}
inline ::celeritas::proto::client::client_debug_request* PROTOBUF_NONNULL client_player_request::_internal_mutable_debug() {
  if (payload_case() != kDebug) {
    clear_payload();
    set_has_debug();
    _impl_.payload_.debug_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::celeritas::proto::client::client_debug_request>(GetArena()));
  }
  return reinterpret_cast<::celeritas::proto::client::client_debug_request*>(_impl_.payload_.debug_);
}
inline ::celeritas::proto::client::client_debug_request* PROTOBUF_NONNULL client_player_request::mutable_debug()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::celeritas::proto::client::client_debug_request* _msg = _internal_mutable_debug();
  // @@protoc_insertion_point(field_mutable:celeritas.proto.client.client_player_request.debug)
  return _msg;
}

// .celeritas.proto.client.client_role_request role = 4;
inline bool client_player_request::has_role() const {
  return payload_case() == kRole;
}
inline bool client_player_request::_internal_has_role() const {
  return payload_case() == kRole;
}
inline void client_player_request::set_has_role() {
  _impl_._oneof_case_[0] = kRole;
}
inline ::celeritas::proto::client::client_role_request* PROTOBUF_NULLABLE client_player_request::release_role() {
  // @@protoc_insertion_point(field_release:celeritas.proto.client.client_player_request.role)
  if (payload_case() == kRole) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::celeritas::proto::client::client_role_request*>(_impl_.payload_.role_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.role_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::celeritas::proto::client::client_role_request& client_player_request::_internal_role() const {
  return payload_case() == kRole ? *reinterpret_cast<::celeritas::proto::client::client_role_request*>(_impl_.payload_.role_) : reinterpret_cast<::celeritas::proto::client::client_role_request&>(::celeritas::proto::client::_client_role_request_default_instance_);
}
inline const ::celeritas::proto::client::client_role_request& client_player_request::role() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:celeritas.proto.client.client_player_request.role)
  return _internal_role();
}
inline ::celeritas::proto::client::client_role_request* PROTOBUF_NULLABLE client_player_request::unsafe_arena_release_role() {
  // @@protoc_insertion_point(field_unsafe_arena_release:celeritas.proto.client.client_player_request.role)
  if (payload_case() == kRole) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::celeritas::proto::client::client_role_request*>(_impl_.payload_.role_);
    _impl_.payload_.role_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void client_player_request::unsafe_arena_set_allocated_role(
    ::celeritas::proto::client::client_role_request* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_role();
    _impl_.payload_.role_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:celeritas.proto.client.client_player_request.role)
}
inline ::celeritas::proto::client::client_role_request* PROTOBUF_NONNULL client_player_request::_internal_mutable_role() {
  if (payload_case() != kRole) {
    clear_payload();
    set_has_role();
    _impl_.payload_.role_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::celeritas::proto::client::client_role_request>(GetArena()));
  }
  return reinterpret_cast<::celeritas::proto::client::client_role_request*>(_impl_.payload_.role_);
}
inline ::celeritas::proto::client::client_role_request* PROTOBUF_NONNULL client_player_request::mutable_role()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::celeritas::proto::client::client_role_request* _msg = _internal_mutable_role();
  // @@protoc_insertion_point(field_mutable:celeritas.proto.client.client_player_request.role)
  return _msg;
}

// .celeritas.proto.client.client_red_dot_request red_dot = 5;
inline bool client_player_request::has_red_dot() const {
  return payload_case() == kRedDot;
}
inline bool client_player_request::_internal_has_red_dot() const {
  return payload_case() == kRedDot;
}
inline void client_player_request::set_has_red_dot() {
  _impl_._oneof_case_[0] = kRedDot;
}
inline ::celeritas::proto::client::client_red_dot_request* PROTOBUF_NULLABLE client_player_request::release_red_dot() {
  // @@protoc_insertion_point(field_release:celeritas.proto.client.client_player_request.red_dot)
  if (payload_case() == kRedDot) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::celeritas::proto::client::client_red_dot_request*>(_impl_.payload_.red_dot_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.red_dot_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::celeritas::proto::client::client_red_dot_request& client_player_request::_internal_red_dot() const {
  return payload_case() == kRedDot ? *reinterpret_cast<::celeritas::proto::client::client_red_dot_request*>(_impl_.payload_.red_dot_) : reinterpret_cast<::celeritas::proto::client::client_red_dot_request&>(::celeritas::proto::client::_client_red_dot_request_default_instance_);
}
inline const ::celeritas::proto::client::client_red_dot_request& client_player_request::red_dot() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:celeritas.proto.client.client_player_request.red_dot)
  return _internal_red_dot();
}
inline ::celeritas::proto::client::client_red_dot_request* PROTOBUF_NULLABLE client_player_request::unsafe_arena_release_red_dot() {
  // @@protoc_insertion_point(field_unsafe_arena_release:celeritas.proto.client.client_player_request.red_dot)
  if (payload_case() == kRedDot) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::celeritas::proto::client::client_red_dot_request*>(_impl_.payload_.red_dot_);
    _impl_.payload_.red_dot_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void client_player_request::unsafe_arena_set_allocated_red_dot(
    ::celeritas::proto::client::client_red_dot_request* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_red_dot();
    _impl_.payload_.red_dot_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:celeritas.proto.client.client_player_request.red_dot)
}
inline ::celeritas::proto::client::client_red_dot_request* PROTOBUF_NONNULL client_player_request::_internal_mutable_red_dot() {
  if (payload_case() != kRedDot) {
    clear_payload();
    set_has_red_dot();
    _impl_.payload_.red_dot_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::celeritas::proto::client::client_red_dot_request>(GetArena()));
  }
  return reinterpret_cast<::celeritas::proto::client::client_red_dot_request*>(_impl_.payload_.red_dot_);
}
inline ::celeritas::proto::client::client_red_dot_request* PROTOBUF_NONNULL client_player_request::mutable_red_dot()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::celeritas::proto::client::client_red_dot_request* _msg = _internal_mutable_red_dot();
  // @@protoc_insertion_point(field_mutable:celeritas.proto.client.client_player_request.red_dot)
  return _msg;
}

// .celeritas.proto.client.client_item_request item = 6;
inline bool client_player_request::has_item() const {
  return payload_case() == kItem;
}
inline bool client_player_request::_internal_has_item() const {
  return payload_case() == kItem;
}
inline void client_player_request::set_has_item() {
  _impl_._oneof_case_[0] = kItem;
}
inline ::celeritas::proto::client::client_item_request* PROTOBUF_NULLABLE client_player_request::release_item() {
  // @@protoc_insertion_point(field_release:celeritas.proto.client.client_player_request.item)
  if (payload_case() == kItem) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::celeritas::proto::client::client_item_request*>(_impl_.payload_.item_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.item_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::celeritas::proto::client::client_item_request& client_player_request::_internal_item() const {
  return payload_case() == kItem ? *reinterpret_cast<::celeritas::proto::client::client_item_request*>(_impl_.payload_.item_) : reinterpret_cast<::celeritas::proto::client::client_item_request&>(::celeritas::proto::client::_client_item_request_default_instance_);
}
inline const ::celeritas::proto::client::client_item_request& client_player_request::item() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:celeritas.proto.client.client_player_request.item)
  return _internal_item();
}
inline ::celeritas::proto::client::client_item_request* PROTOBUF_NULLABLE client_player_request::unsafe_arena_release_item() {
  // @@protoc_insertion_point(field_unsafe_arena_release:celeritas.proto.client.client_player_request.item)
  if (payload_case() == kItem) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::celeritas::proto::client::client_item_request*>(_impl_.payload_.item_);
    _impl_.payload_.item_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void client_player_request::unsafe_arena_set_allocated_item(
    ::celeritas::proto::client::client_item_request* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_item();
    _impl_.payload_.item_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:celeritas.proto.client.client_player_request.item)
}
inline ::celeritas::proto::client::client_item_request* PROTOBUF_NONNULL client_player_request::_internal_mutable_item() {
  if (payload_case() != kItem) {
    clear_payload();
    set_has_item();
    _impl_.payload_.item_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::celeritas::proto::client::client_item_request>(GetArena()));
  }
  return reinterpret_cast<::celeritas::proto::client::client_item_request*>(_impl_.payload_.item_);
}
inline ::celeritas::proto::client::client_item_request* PROTOBUF_NONNULL client_player_request::mutable_item()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::celeritas::proto::client::client_item_request* _msg = _internal_mutable_item();
  // @@protoc_insertion_point(field_mutable:celeritas.proto.client.client_player_request.item)
  return _msg;
}

// .celeritas.proto.client.client_develop_request develop = 7;
inline bool client_player_request::has_develop() const {
  return payload_case() == kDevelop;
}
inline bool client_player_request::_internal_has_develop() const {
  return payload_case() == kDevelop;
}
inline void client_player_request::set_has_develop() {
  _impl_._oneof_case_[0] = kDevelop;
}
inline ::celeritas::proto::client::client_develop_request* PROTOBUF_NULLABLE client_player_request::release_develop() {
  // @@protoc_insertion_point(field_release:celeritas.proto.client.client_player_request.develop)
  if (payload_case() == kDevelop) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::celeritas::proto::client::client_develop_request*>(_impl_.payload_.develop_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.develop_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::celeritas::proto::client::client_develop_request& client_player_request::_internal_develop() const {
  return payload_case() == kDevelop ? *reinterpret_cast<::celeritas::proto::client::client_develop_request*>(_impl_.payload_.develop_) : reinterpret_cast<::celeritas::proto::client::client_develop_request&>(::celeritas::proto::client::_client_develop_request_default_instance_);
}
inline const ::celeritas::proto::client::client_develop_request& client_player_request::develop() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:celeritas.proto.client.client_player_request.develop)
  return _internal_develop();
}
inline ::celeritas::proto::client::client_develop_request* PROTOBUF_NULLABLE client_player_request::unsafe_arena_release_develop() {
  // @@protoc_insertion_point(field_unsafe_arena_release:celeritas.proto.client.client_player_request.develop)
  if (payload_case() == kDevelop) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::celeritas::proto::client::client_develop_request*>(_impl_.payload_.develop_);
    _impl_.payload_.develop_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void client_player_request::unsafe_arena_set_allocated_develop(
    ::celeritas::proto::client::client_develop_request* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_develop();
    _impl_.payload_.develop_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:celeritas.proto.client.client_player_request.develop)
}
inline ::celeritas::proto::client::client_develop_request* PROTOBUF_NONNULL client_player_request::_internal_mutable_develop() {
  if (payload_case() != kDevelop) {
    clear_payload();
    set_has_develop();
    _impl_.payload_.develop_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::celeritas::proto::client::client_develop_request>(GetArena()));
  }
  return reinterpret_cast<::celeritas::proto::client::client_develop_request*>(_impl_.payload_.develop_);
}
inline ::celeritas::proto::client::client_develop_request* PROTOBUF_NONNULL client_player_request::mutable_develop()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::celeritas::proto::client::client_develop_request* _msg = _internal_mutable_develop();
  // @@protoc_insertion_point(field_mutable:celeritas.proto.client.client_player_request.develop)
  return _msg;
}

// .celeritas.proto.client.client_mail_request mail = 8;
inline bool client_player_request::has_mail() const {
  return payload_case() == kMail;
}
inline bool client_player_request::_internal_has_mail() const {
  return payload_case() == kMail;
}
inline void client_player_request::set_has_mail() {
  _impl_._oneof_case_[0] = kMail;
}
inline ::celeritas::proto::client::client_mail_request* PROTOBUF_NULLABLE client_player_request::release_mail() {
  // @@protoc_insertion_point(field_release:celeritas.proto.client.client_player_request.mail)
  if (payload_case() == kMail) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::celeritas::proto::client::client_mail_request*>(_impl_.payload_.mail_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.mail_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::celeritas::proto::client::client_mail_request& client_player_request::_internal_mail() const {
  return payload_case() == kMail ? *reinterpret_cast<::celeritas::proto::client::client_mail_request*>(_impl_.payload_.mail_) : reinterpret_cast<::celeritas::proto::client::client_mail_request&>(::celeritas::proto::client::_client_mail_request_default_instance_);
}
inline const ::celeritas::proto::client::client_mail_request& client_player_request::mail() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:celeritas.proto.client.client_player_request.mail)
  return _internal_mail();
}
inline ::celeritas::proto::client::client_mail_request* PROTOBUF_NULLABLE client_player_request::unsafe_arena_release_mail() {
  // @@protoc_insertion_point(field_unsafe_arena_release:celeritas.proto.client.client_player_request.mail)
  if (payload_case() == kMail) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::celeritas::proto::client::client_mail_request*>(_impl_.payload_.mail_);
    _impl_.payload_.mail_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void client_player_request::unsafe_arena_set_allocated_mail(
    ::celeritas::proto::client::client_mail_request* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_mail();
    _impl_.payload_.mail_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:celeritas.proto.client.client_player_request.mail)
}
inline ::celeritas::proto::client::client_mail_request* PROTOBUF_NONNULL client_player_request::_internal_mutable_mail() {
  if (payload_case() != kMail) {
    clear_payload();
    set_has_mail();
    _impl_.payload_.mail_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::celeritas::proto::client::client_mail_request>(GetArena()));
  }
  return reinterpret_cast<::celeritas::proto::client::client_mail_request*>(_impl_.payload_.mail_);
}
inline ::celeritas::proto::client::client_mail_request* PROTOBUF_NONNULL client_player_request::mutable_mail()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::celeritas::proto::client::client_mail_request* _msg = _internal_mutable_mail();
  // @@protoc_insertion_point(field_mutable:celeritas.proto.client.client_player_request.mail)
  return _msg;
}

inline bool client_player_request::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void client_player_request::clear_has_payload() {
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline client_player_request::PayloadCase client_player_request::payload_case() const {
  return client_player_request::PayloadCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// client_player_response

// .celeritas.proto.client.client_login_response login = 1;
inline bool client_player_response::has_login() const {
  return payload_case() == kLogin;
}
inline bool client_player_response::_internal_has_login() const {
  return payload_case() == kLogin;
}
inline void client_player_response::set_has_login() {
  _impl_._oneof_case_[0] = kLogin;
}
inline ::celeritas::proto::client::client_login_response* PROTOBUF_NULLABLE client_player_response::release_login() {
  // @@protoc_insertion_point(field_release:celeritas.proto.client.client_player_response.login)
  if (payload_case() == kLogin) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::celeritas::proto::client::client_login_response*>(_impl_.payload_.login_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.login_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::celeritas::proto::client::client_login_response& client_player_response::_internal_login() const {
  return payload_case() == kLogin ? *reinterpret_cast<::celeritas::proto::client::client_login_response*>(_impl_.payload_.login_) : reinterpret_cast<::celeritas::proto::client::client_login_response&>(::celeritas::proto::client::_client_login_response_default_instance_);
}
inline const ::celeritas::proto::client::client_login_response& client_player_response::login() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:celeritas.proto.client.client_player_response.login)
  return _internal_login();
}
inline ::celeritas::proto::client::client_login_response* PROTOBUF_NULLABLE client_player_response::unsafe_arena_release_login() {
  // @@protoc_insertion_point(field_unsafe_arena_release:celeritas.proto.client.client_player_response.login)
  if (payload_case() == kLogin) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::celeritas::proto::client::client_login_response*>(_impl_.payload_.login_);
    _impl_.payload_.login_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void client_player_response::unsafe_arena_set_allocated_login(
    ::celeritas::proto::client::client_login_response* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_login();
    _impl_.payload_.login_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:celeritas.proto.client.client_player_response.login)
}
inline ::celeritas::proto::client::client_login_response* PROTOBUF_NONNULL client_player_response::_internal_mutable_login() {
  if (payload_case() != kLogin) {
    clear_payload();
    set_has_login();
    _impl_.payload_.login_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::celeritas::proto::client::client_login_response>(GetArena()));
  }
  return reinterpret_cast<::celeritas::proto::client::client_login_response*>(_impl_.payload_.login_);
}
inline ::celeritas::proto::client::client_login_response* PROTOBUF_NONNULL client_player_response::mutable_login()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::celeritas::proto::client::client_login_response* _msg = _internal_mutable_login();
  // @@protoc_insertion_point(field_mutable:celeritas.proto.client.client_player_response.login)
  return _msg;
}

// .celeritas.proto.client.client_heartbeat_response heartbeat = 2;
inline bool client_player_response::has_heartbeat() const {
  return payload_case() == kHeartbeat;
}
inline bool client_player_response::_internal_has_heartbeat() const {
  return payload_case() == kHeartbeat;
}
inline void client_player_response::set_has_heartbeat() {
  _impl_._oneof_case_[0] = kHeartbeat;
}
inline ::celeritas::proto::client::client_heartbeat_response* PROTOBUF_NULLABLE client_player_response::release_heartbeat() {
  // @@protoc_insertion_point(field_release:celeritas.proto.client.client_player_response.heartbeat)
  if (payload_case() == kHeartbeat) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::celeritas::proto::client::client_heartbeat_response*>(_impl_.payload_.heartbeat_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.heartbeat_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::celeritas::proto::client::client_heartbeat_response& client_player_response::_internal_heartbeat() const {
  return payload_case() == kHeartbeat ? *reinterpret_cast<::celeritas::proto::client::client_heartbeat_response*>(_impl_.payload_.heartbeat_) : reinterpret_cast<::celeritas::proto::client::client_heartbeat_response&>(::celeritas::proto::client::_client_heartbeat_response_default_instance_);
}
inline const ::celeritas::proto::client::client_heartbeat_response& client_player_response::heartbeat() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:celeritas.proto.client.client_player_response.heartbeat)
  return _internal_heartbeat();
}
inline ::celeritas::proto::client::client_heartbeat_response* PROTOBUF_NULLABLE client_player_response::unsafe_arena_release_heartbeat() {
  // @@protoc_insertion_point(field_unsafe_arena_release:celeritas.proto.client.client_player_response.heartbeat)
  if (payload_case() == kHeartbeat) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::celeritas::proto::client::client_heartbeat_response*>(_impl_.payload_.heartbeat_);
    _impl_.payload_.heartbeat_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void client_player_response::unsafe_arena_set_allocated_heartbeat(
    ::celeritas::proto::client::client_heartbeat_response* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_heartbeat();
    _impl_.payload_.heartbeat_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:celeritas.proto.client.client_player_response.heartbeat)
}
inline ::celeritas::proto::client::client_heartbeat_response* PROTOBUF_NONNULL client_player_response::_internal_mutable_heartbeat() {
  if (payload_case() != kHeartbeat) {
    clear_payload();
    set_has_heartbeat();
    _impl_.payload_.heartbeat_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::celeritas::proto::client::client_heartbeat_response>(GetArena()));
  }
  return reinterpret_cast<::celeritas::proto::client::client_heartbeat_response*>(_impl_.payload_.heartbeat_);
}
inline ::celeritas::proto::client::client_heartbeat_response* PROTOBUF_NONNULL client_player_response::mutable_heartbeat()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::celeritas::proto::client::client_heartbeat_response* _msg = _internal_mutable_heartbeat();
  // @@protoc_insertion_point(field_mutable:celeritas.proto.client.client_player_response.heartbeat)
  return _msg;
}

// .celeritas.proto.client.client_debug_response debug = 3;
inline bool client_player_response::has_debug() const {
  return payload_case() == kDebug;
}
inline bool client_player_response::_internal_has_debug() const {
  return payload_case() == kDebug;
}
inline void client_player_response::set_has_debug() {
  _impl_._oneof_case_[0] = kDebug;
}
inline ::celeritas::proto::client::client_debug_response* PROTOBUF_NULLABLE client_player_response::release_debug() {
  // @@protoc_insertion_point(field_release:celeritas.proto.client.client_player_response.debug)
  if (payload_case() == kDebug) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::celeritas::proto::client::client_debug_response*>(_impl_.payload_.debug_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.debug_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::celeritas::proto::client::client_debug_response& client_player_response::_internal_debug() const {
  return payload_case() == kDebug ? *reinterpret_cast<::celeritas::proto::client::client_debug_response*>(_impl_.payload_.debug_) : reinterpret_cast<::celeritas::proto::client::client_debug_response&>(::celeritas::proto::client::_client_debug_response_default_instance_);
}
inline const ::celeritas::proto::client::client_debug_response& client_player_response::debug() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:celeritas.proto.client.client_player_response.debug)
  return _internal_debug();
}
inline ::celeritas::proto::client::client_debug_response* PROTOBUF_NULLABLE client_player_response::unsafe_arena_release_debug() {
  // @@protoc_insertion_point(field_unsafe_arena_release:celeritas.proto.client.client_player_response.debug)
  if (payload_case() == kDebug) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::celeritas::proto::client::client_debug_response*>(_impl_.payload_.debug_);
    _impl_.payload_.debug_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void client_player_response::unsafe_arena_set_allocated_debug(
    ::celeritas::proto::client::client_debug_response* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_debug();
    _impl_.payload_.debug_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:celeritas.proto.client.client_player_response.debug)
}
inline ::celeritas::proto::client::client_debug_response* PROTOBUF_NONNULL client_player_response::_internal_mutable_debug() {
  if (payload_case() != kDebug) {
    clear_payload();
    set_has_debug();
    _impl_.payload_.debug_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::celeritas::proto::client::client_debug_response>(GetArena()));
  }
  return reinterpret_cast<::celeritas::proto::client::client_debug_response*>(_impl_.payload_.debug_);
}
inline ::celeritas::proto::client::client_debug_response* PROTOBUF_NONNULL client_player_response::mutable_debug()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::celeritas::proto::client::client_debug_response* _msg = _internal_mutable_debug();
  // @@protoc_insertion_point(field_mutable:celeritas.proto.client.client_player_response.debug)
  return _msg;
}

// .celeritas.proto.client.client_role_response role = 4;
inline bool client_player_response::has_role() const {
  return payload_case() == kRole;
}
inline bool client_player_response::_internal_has_role() const {
  return payload_case() == kRole;
}
inline void client_player_response::set_has_role() {
  _impl_._oneof_case_[0] = kRole;
}
inline ::celeritas::proto::client::client_role_response* PROTOBUF_NULLABLE client_player_response::release_role() {
  // @@protoc_insertion_point(field_release:celeritas.proto.client.client_player_response.role)
  if (payload_case() == kRole) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::celeritas::proto::client::client_role_response*>(_impl_.payload_.role_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.role_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::celeritas::proto::client::client_role_response& client_player_response::_internal_role() const {
  return payload_case() == kRole ? *reinterpret_cast<::celeritas::proto::client::client_role_response*>(_impl_.payload_.role_) : reinterpret_cast<::celeritas::proto::client::client_role_response&>(::celeritas::proto::client::_client_role_response_default_instance_);
}
inline const ::celeritas::proto::client::client_role_response& client_player_response::role() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:celeritas.proto.client.client_player_response.role)
  return _internal_role();
}
inline ::celeritas::proto::client::client_role_response* PROTOBUF_NULLABLE client_player_response::unsafe_arena_release_role() {
  // @@protoc_insertion_point(field_unsafe_arena_release:celeritas.proto.client.client_player_response.role)
  if (payload_case() == kRole) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::celeritas::proto::client::client_role_response*>(_impl_.payload_.role_);
    _impl_.payload_.role_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void client_player_response::unsafe_arena_set_allocated_role(
    ::celeritas::proto::client::client_role_response* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_role();
    _impl_.payload_.role_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:celeritas.proto.client.client_player_response.role)
}
inline ::celeritas::proto::client::client_role_response* PROTOBUF_NONNULL client_player_response::_internal_mutable_role() {
  if (payload_case() != kRole) {
    clear_payload();
    set_has_role();
    _impl_.payload_.role_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::celeritas::proto::client::client_role_response>(GetArena()));
  }
  return reinterpret_cast<::celeritas::proto::client::client_role_response*>(_impl_.payload_.role_);
}
inline ::celeritas::proto::client::client_role_response* PROTOBUF_NONNULL client_player_response::mutable_role()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::celeritas::proto::client::client_role_response* _msg = _internal_mutable_role();
  // @@protoc_insertion_point(field_mutable:celeritas.proto.client.client_player_response.role)
  return _msg;
}

// .celeritas.proto.client.client_red_dot_response red_dot = 5;
inline bool client_player_response::has_red_dot() const {
  return payload_case() == kRedDot;
}
inline bool client_player_response::_internal_has_red_dot() const {
  return payload_case() == kRedDot;
}
inline void client_player_response::set_has_red_dot() {
  _impl_._oneof_case_[0] = kRedDot;
}
inline ::celeritas::proto::client::client_red_dot_response* PROTOBUF_NULLABLE client_player_response::release_red_dot() {
  // @@protoc_insertion_point(field_release:celeritas.proto.client.client_player_response.red_dot)
  if (payload_case() == kRedDot) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::celeritas::proto::client::client_red_dot_response*>(_impl_.payload_.red_dot_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.red_dot_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::celeritas::proto::client::client_red_dot_response& client_player_response::_internal_red_dot() const {
  return payload_case() == kRedDot ? *reinterpret_cast<::celeritas::proto::client::client_red_dot_response*>(_impl_.payload_.red_dot_) : reinterpret_cast<::celeritas::proto::client::client_red_dot_response&>(::celeritas::proto::client::_client_red_dot_response_default_instance_);
}
inline const ::celeritas::proto::client::client_red_dot_response& client_player_response::red_dot() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:celeritas.proto.client.client_player_response.red_dot)
  return _internal_red_dot();
}
inline ::celeritas::proto::client::client_red_dot_response* PROTOBUF_NULLABLE client_player_response::unsafe_arena_release_red_dot() {
  // @@protoc_insertion_point(field_unsafe_arena_release:celeritas.proto.client.client_player_response.red_dot)
  if (payload_case() == kRedDot) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::celeritas::proto::client::client_red_dot_response*>(_impl_.payload_.red_dot_);
    _impl_.payload_.red_dot_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void client_player_response::unsafe_arena_set_allocated_red_dot(
    ::celeritas::proto::client::client_red_dot_response* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_red_dot();
    _impl_.payload_.red_dot_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:celeritas.proto.client.client_player_response.red_dot)
}
inline ::celeritas::proto::client::client_red_dot_response* PROTOBUF_NONNULL client_player_response::_internal_mutable_red_dot() {
  if (payload_case() != kRedDot) {
    clear_payload();
    set_has_red_dot();
    _impl_.payload_.red_dot_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::celeritas::proto::client::client_red_dot_response>(GetArena()));
  }
  return reinterpret_cast<::celeritas::proto::client::client_red_dot_response*>(_impl_.payload_.red_dot_);
}
inline ::celeritas::proto::client::client_red_dot_response* PROTOBUF_NONNULL client_player_response::mutable_red_dot()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::celeritas::proto::client::client_red_dot_response* _msg = _internal_mutable_red_dot();
  // @@protoc_insertion_point(field_mutable:celeritas.proto.client.client_player_response.red_dot)
  return _msg;
}

// .celeritas.proto.client.client_item_response item = 6;
inline bool client_player_response::has_item() const {
  return payload_case() == kItem;
}
inline bool client_player_response::_internal_has_item() const {
  return payload_case() == kItem;
}
inline void client_player_response::set_has_item() {
  _impl_._oneof_case_[0] = kItem;
}
inline ::celeritas::proto::client::client_item_response* PROTOBUF_NULLABLE client_player_response::release_item() {
  // @@protoc_insertion_point(field_release:celeritas.proto.client.client_player_response.item)
  if (payload_case() == kItem) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::celeritas::proto::client::client_item_response*>(_impl_.payload_.item_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.item_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::celeritas::proto::client::client_item_response& client_player_response::_internal_item() const {
  return payload_case() == kItem ? *reinterpret_cast<::celeritas::proto::client::client_item_response*>(_impl_.payload_.item_) : reinterpret_cast<::celeritas::proto::client::client_item_response&>(::celeritas::proto::client::_client_item_response_default_instance_);
}
inline const ::celeritas::proto::client::client_item_response& client_player_response::item() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:celeritas.proto.client.client_player_response.item)
  return _internal_item();
}
inline ::celeritas::proto::client::client_item_response* PROTOBUF_NULLABLE client_player_response::unsafe_arena_release_item() {
  // @@protoc_insertion_point(field_unsafe_arena_release:celeritas.proto.client.client_player_response.item)
  if (payload_case() == kItem) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::celeritas::proto::client::client_item_response*>(_impl_.payload_.item_);
    _impl_.payload_.item_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void client_player_response::unsafe_arena_set_allocated_item(
    ::celeritas::proto::client::client_item_response* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_item();
    _impl_.payload_.item_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:celeritas.proto.client.client_player_response.item)
}
inline ::celeritas::proto::client::client_item_response* PROTOBUF_NONNULL client_player_response::_internal_mutable_item() {
  if (payload_case() != kItem) {
    clear_payload();
    set_has_item();
    _impl_.payload_.item_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::celeritas::proto::client::client_item_response>(GetArena()));
  }
  return reinterpret_cast<::celeritas::proto::client::client_item_response*>(_impl_.payload_.item_);
}
inline ::celeritas::proto::client::client_item_response* PROTOBUF_NONNULL client_player_response::mutable_item()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::celeritas::proto::client::client_item_response* _msg = _internal_mutable_item();
  // @@protoc_insertion_point(field_mutable:celeritas.proto.client.client_player_response.item)
  return _msg;
}

// .celeritas.proto.client.client_develop_response develop = 7;
inline bool client_player_response::has_develop() const {
  return payload_case() == kDevelop;
}
inline bool client_player_response::_internal_has_develop() const {
  return payload_case() == kDevelop;
}
inline void client_player_response::set_has_develop() {
  _impl_._oneof_case_[0] = kDevelop;
}
inline ::celeritas::proto::client::client_develop_response* PROTOBUF_NULLABLE client_player_response::release_develop() {
  // @@protoc_insertion_point(field_release:celeritas.proto.client.client_player_response.develop)
  if (payload_case() == kDevelop) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::celeritas::proto::client::client_develop_response*>(_impl_.payload_.develop_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.develop_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::celeritas::proto::client::client_develop_response& client_player_response::_internal_develop() const {
  return payload_case() == kDevelop ? *reinterpret_cast<::celeritas::proto::client::client_develop_response*>(_impl_.payload_.develop_) : reinterpret_cast<::celeritas::proto::client::client_develop_response&>(::celeritas::proto::client::_client_develop_response_default_instance_);
}
inline const ::celeritas::proto::client::client_develop_response& client_player_response::develop() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:celeritas.proto.client.client_player_response.develop)
  return _internal_develop();
}
inline ::celeritas::proto::client::client_develop_response* PROTOBUF_NULLABLE client_player_response::unsafe_arena_release_develop() {
  // @@protoc_insertion_point(field_unsafe_arena_release:celeritas.proto.client.client_player_response.develop)
  if (payload_case() == kDevelop) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::celeritas::proto::client::client_develop_response*>(_impl_.payload_.develop_);
    _impl_.payload_.develop_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void client_player_response::unsafe_arena_set_allocated_develop(
    ::celeritas::proto::client::client_develop_response* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_develop();
    _impl_.payload_.develop_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:celeritas.proto.client.client_player_response.develop)
}
inline ::celeritas::proto::client::client_develop_response* PROTOBUF_NONNULL client_player_response::_internal_mutable_develop() {
  if (payload_case() != kDevelop) {
    clear_payload();
    set_has_develop();
    _impl_.payload_.develop_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::celeritas::proto::client::client_develop_response>(GetArena()));
  }
  return reinterpret_cast<::celeritas::proto::client::client_develop_response*>(_impl_.payload_.develop_);
}
inline ::celeritas::proto::client::client_develop_response* PROTOBUF_NONNULL client_player_response::mutable_develop()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::celeritas::proto::client::client_develop_response* _msg = _internal_mutable_develop();
  // @@protoc_insertion_point(field_mutable:celeritas.proto.client.client_player_response.develop)
  return _msg;
}

// .celeritas.proto.client.client_mail_response mail = 8;
inline bool client_player_response::has_mail() const {
  return payload_case() == kMail;
}
inline bool client_player_response::_internal_has_mail() const {
  return payload_case() == kMail;
}
inline void client_player_response::set_has_mail() {
  _impl_._oneof_case_[0] = kMail;
}
inline ::celeritas::proto::client::client_mail_response* PROTOBUF_NULLABLE client_player_response::release_mail() {
  // @@protoc_insertion_point(field_release:celeritas.proto.client.client_player_response.mail)
  if (payload_case() == kMail) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::celeritas::proto::client::client_mail_response*>(_impl_.payload_.mail_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.mail_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::celeritas::proto::client::client_mail_response& client_player_response::_internal_mail() const {
  return payload_case() == kMail ? *reinterpret_cast<::celeritas::proto::client::client_mail_response*>(_impl_.payload_.mail_) : reinterpret_cast<::celeritas::proto::client::client_mail_response&>(::celeritas::proto::client::_client_mail_response_default_instance_);
}
inline const ::celeritas::proto::client::client_mail_response& client_player_response::mail() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:celeritas.proto.client.client_player_response.mail)
  return _internal_mail();
}
inline ::celeritas::proto::client::client_mail_response* PROTOBUF_NULLABLE client_player_response::unsafe_arena_release_mail() {
  // @@protoc_insertion_point(field_unsafe_arena_release:celeritas.proto.client.client_player_response.mail)
  if (payload_case() == kMail) {
    clear_has_payload();
    auto* temp = reinterpret_cast<::celeritas::proto::client::client_mail_response*>(_impl_.payload_.mail_);
    _impl_.payload_.mail_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void client_player_response::unsafe_arena_set_allocated_mail(
    ::celeritas::proto::client::client_mail_response* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_mail();
    _impl_.payload_.mail_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:celeritas.proto.client.client_player_response.mail)
}
inline ::celeritas::proto::client::client_mail_response* PROTOBUF_NONNULL client_player_response::_internal_mutable_mail() {
  if (payload_case() != kMail) {
    clear_payload();
    set_has_mail();
    _impl_.payload_.mail_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::celeritas::proto::client::client_mail_response>(GetArena()));
  }
  return reinterpret_cast<::celeritas::proto::client::client_mail_response*>(_impl_.payload_.mail_);
}
inline ::celeritas::proto::client::client_mail_response* PROTOBUF_NONNULL client_player_response::mutable_mail()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::celeritas::proto::client::client_mail_response* _msg = _internal_mutable_mail();
  // @@protoc_insertion_point(field_mutable:celeritas.proto.client.client_player_response.mail)
  return _msg;
}

inline bool client_player_response::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void client_player_response::clear_has_payload() {
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline client_player_response::PayloadCase client_player_response::payload_case() const {
  return client_player_response::PayloadCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace client
}  // namespace proto
}  // namespace celeritas


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // proto_2fclient_2fplayer_2fplayer_2eproto_2epb_2eh
