// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/service/service_response.proto
// Protobuf C++ Version: 6.31.1

#ifndef proto_2fservice_2fservice_5fresponse_2eproto_2epb_2eh
#define proto_2fservice_2fservice_5fresponse_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "proto/service/registry.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_proto_2fservice_2fservice_5fresponse_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2fservice_2fservice_5fresponse_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_proto_2fservice_2fservice_5fresponse_2eproto;
}  // extern "C"
namespace celeritas {
namespace proto {
namespace service {
class service_response;
struct service_responseDefaultTypeInternal;
extern service_responseDefaultTypeInternal _service_response_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull service_response_class_data_;
}  // namespace service
}  // namespace proto
}  // namespace celeritas
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace celeritas {
namespace proto {
namespace service {

// ===================================================================


// -------------------------------------------------------------------

class service_response final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:celeritas.proto.service.service_response) */ {
 public:
  inline service_response() : service_response(nullptr) {}
  ~service_response() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(service_response* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(service_response));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR service_response(::google::protobuf::internal::ConstantInitialized);

  inline service_response(const service_response& from) : service_response(nullptr, from) {}
  inline service_response(service_response&& from) noexcept
      : service_response(nullptr, ::std::move(from)) {}
  inline service_response& operator=(const service_response& from) {
    CopyFrom(from);
    return *this;
  }
  inline service_response& operator=(service_response&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const service_response& default_instance() {
    return *reinterpret_cast<const service_response*>(
        &_service_response_default_instance_);
  }
  enum PayloadCase {
    kRegistry = 1,
    PAYLOAD_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(service_response& a, service_response& b) { a.Swap(&b); }
  inline void Swap(service_response* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(service_response* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  service_response* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<service_response>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const service_response& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const service_response& from) { service_response::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(service_response* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "celeritas.proto.service.service_response"; }

 protected:
  explicit service_response(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  service_response(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const service_response& from);
  service_response(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, service_response&& from) noexcept
      : service_response(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kRegistryFieldNumber = 1,
  };
  // .celeritas.proto.service.service_registry_response registry = 1;
  bool has_registry() const;
  private:
  bool _internal_has_registry() const;

  public:
  void clear_registry() ;
  const ::celeritas::proto::service::service_registry_response& registry() const;
  [[nodiscard]] ::celeritas::proto::service::service_registry_response* PROTOBUF_NULLABLE release_registry();
  ::celeritas::proto::service::service_registry_response* PROTOBUF_NONNULL mutable_registry();
  void set_allocated_registry(::celeritas::proto::service::service_registry_response* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_registry(::celeritas::proto::service::service_registry_response* PROTOBUF_NULLABLE value);
  ::celeritas::proto::service::service_registry_response* PROTOBUF_NULLABLE unsafe_arena_release_registry();

  private:
  const ::celeritas::proto::service::service_registry_response& _internal_registry() const;
  ::celeritas::proto::service::service_registry_response* PROTOBUF_NONNULL _internal_mutable_registry();

  public:
  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:celeritas.proto.service.service_response)
 private:
  class _Internal;
  void set_has_registry();
  inline bool has_payload() const;
  inline void clear_has_payload();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const service_response& from_msg);
    union PayloadUnion {
      constexpr PayloadUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::celeritas::proto::service::service_registry_response* PROTOBUF_NULLABLE registry_;
    } payload_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fservice_2fservice_5fresponse_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull service_response_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// service_response

// .celeritas.proto.service.service_registry_response registry = 1;
inline bool service_response::has_registry() const {
  return payload_case() == kRegistry;
}
inline bool service_response::_internal_has_registry() const {
  return payload_case() == kRegistry;
}
inline void service_response::set_has_registry() {
  _impl_._oneof_case_[0] = kRegistry;
}
inline ::celeritas::proto::service::service_registry_response* PROTOBUF_NULLABLE service_response::release_registry() {
  // @@protoc_insertion_point(field_release:celeritas.proto.service.service_response.registry)
  if (payload_case() == kRegistry) {
    clear_has_payload();
    auto* temp = _impl_.payload_.registry_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.registry_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::celeritas::proto::service::service_registry_response& service_response::_internal_registry() const {
  return payload_case() == kRegistry ? *_impl_.payload_.registry_ : reinterpret_cast<::celeritas::proto::service::service_registry_response&>(::celeritas::proto::service::_service_registry_response_default_instance_);
}
inline const ::celeritas::proto::service::service_registry_response& service_response::registry() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:celeritas.proto.service.service_response.registry)
  return _internal_registry();
}
inline ::celeritas::proto::service::service_registry_response* PROTOBUF_NULLABLE service_response::unsafe_arena_release_registry() {
  // @@protoc_insertion_point(field_unsafe_arena_release:celeritas.proto.service.service_response.registry)
  if (payload_case() == kRegistry) {
    clear_has_payload();
    auto* temp = _impl_.payload_.registry_;
    _impl_.payload_.registry_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void service_response::unsafe_arena_set_allocated_registry(
    ::celeritas::proto::service::service_registry_response* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_registry();
    _impl_.payload_.registry_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:celeritas.proto.service.service_response.registry)
}
inline ::celeritas::proto::service::service_registry_response* PROTOBUF_NONNULL service_response::_internal_mutable_registry() {
  if (payload_case() != kRegistry) {
    clear_payload();
    set_has_registry();
    _impl_.payload_.registry_ = 
        ::google::protobuf::Message::DefaultConstruct<::celeritas::proto::service::service_registry_response>(GetArena());
  }
  return _impl_.payload_.registry_;
}
inline ::celeritas::proto::service::service_registry_response* PROTOBUF_NONNULL service_response::mutable_registry()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::celeritas::proto::service::service_registry_response* _msg = _internal_mutable_registry();
  // @@protoc_insertion_point(field_mutable:celeritas.proto.service.service_response.registry)
  return _msg;
}

inline bool service_response::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void service_response::clear_has_payload() {
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline service_response::PayloadCase service_response::payload_case() const {
  return service_response::PayloadCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace service
}  // namespace proto
}  // namespace celeritas


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // proto_2fservice_2fservice_5fresponse_2eproto_2epb_2eh
