syntax = "proto3";

package celeritas.proto.client;

message login_request {
    string token = 1;
    string game_server_id = 2;
    string device_id = 3;
    string app_version = 4;
}

message login_response {
    string session_key = 1;
    int64 character_id = 2;
    int64 current_time = 3;
}

message gateway_login_request {
    int64 account_id = 1;
    string game_server_id = 2;
    string device_id = 3;
    string app_version = 4;
}

message client_login_request {
  oneof payload {
    login_request login = 1;
    gateway_login_request gateway_login = 2;
  }
}

message client_login_response {
  oneof payload {
    login_response login = 1;
  }
}


