syntax = "proto3";

package celeritas.proto.service;

// 重载配置数据库
message reload_config_db_request {
  string db_name = 1;
  int64 id = 2;
}

message reload_config_db_response {
}

// 重载游戏数据库
message reload_game_config_request {
}

message reload_game_config_response {
}

message service_login_request {
    int64 account_id = 1;
    bool new_account = 2;
    int64 account_bind_id = 3;
    bool new_game_server_id = 4;
    string game_server_id = 5;
    string device_id = 6;
    string app_version = 7;
    int64 session_id = 8;
    int32 protocol = 9;
}

message service_login_response {
    int64 current_time = 1;
    int64 session_id = 2;
    int32 protocol = 3;
    string instance_id = 4;
}

message service_player_request {
  oneof payload {
    reload_config_db_request reload_config_db = 1;
    reload_game_config_request reload_game_config = 2;
    service_login_request service_login = 3;
  }
}

message service_player_response {
  oneof payload {
    reload_config_db_response reload_config_db = 1;
    reload_game_config_response reload_game_config = 2;
    service_login_response service_login = 3;
  }
}

