// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/common/common.proto
// Protobuf C++ Version: 6.32.1

#include "proto/common/common.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace celeritas {
namespace proto {
namespace common {

inline constexpr to_gateway_message_header::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        user_id_{::int64_t{0}},
        rpc_{0},
        code_{0} {}

template <typename>
PROTOBUF_CONSTEXPR to_gateway_message_header::to_gateway_message_header(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(to_gateway_message_header_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct to_gateway_message_headerDefaultTypeInternal {
  PROTOBUF_CONSTEXPR to_gateway_message_headerDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~to_gateway_message_headerDefaultTypeInternal() {}
  union {
    to_gateway_message_header _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 to_gateway_message_headerDefaultTypeInternal _to_gateway_message_header_default_instance_;

inline constexpr server_message_header::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        user_id_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR server_message_header::server_message_header(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(server_message_header_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct server_message_headerDefaultTypeInternal {
  PROTOBUF_CONSTEXPR server_message_headerDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~server_message_headerDefaultTypeInternal() {}
  union {
    server_message_header _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 server_message_headerDefaultTypeInternal _server_message_header_default_instance_;

inline constexpr gateway_message_header::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        user_id_{::int64_t{0}},
        rpc_{0} {}

template <typename>
PROTOBUF_CONSTEXPR gateway_message_header::gateway_message_header(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(gateway_message_header_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct gateway_message_headerDefaultTypeInternal {
  PROTOBUF_CONSTEXPR gateway_message_headerDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~gateway_message_headerDefaultTypeInternal() {}
  union {
    gateway_message_header _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 gateway_message_headerDefaultTypeInternal _gateway_message_header_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR empty_message_header::empty_message_header(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(empty_message_header_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct empty_message_headerDefaultTypeInternal {
  PROTOBUF_CONSTEXPR empty_message_headerDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~empty_message_headerDefaultTypeInternal() {}
  union {
    empty_message_header _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 empty_message_headerDefaultTypeInternal _empty_message_header_default_instance_;

inline constexpr client_message_header::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        rpc_{0} {}

template <typename>
PROTOBUF_CONSTEXPR client_message_header::client_message_header(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(client_message_header_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct client_message_headerDefaultTypeInternal {
  PROTOBUF_CONSTEXPR client_message_headerDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~client_message_headerDefaultTypeInternal() {}
  union {
    client_message_header _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 client_message_headerDefaultTypeInternal _client_message_header_default_instance_;

inline constexpr header::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : payload_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR header::header(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(header_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct headerDefaultTypeInternal {
  PROTOBUF_CONSTEXPR headerDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~headerDefaultTypeInternal() {}
  union {
    header _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 headerDefaultTypeInternal _header_default_instance_;
}  // namespace common
}  // namespace proto
}  // namespace celeritas
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_proto_2fcommon_2fcommon_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_proto_2fcommon_2fcommon_2eproto = nullptr;
const ::uint32_t
    TableStruct_proto_2fcommon_2fcommon_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x000, // bitmap
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::celeritas::proto::common::client_message_header, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::celeritas::proto::common::client_message_header, _impl_.rpc_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::celeritas::proto::common::server_message_header, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::celeritas::proto::common::server_message_header, _impl_.user_id_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::celeritas::proto::common::gateway_message_header, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::celeritas::proto::common::gateway_message_header, _impl_.user_id_),
        PROTOBUF_FIELD_OFFSET(::celeritas::proto::common::gateway_message_header, _impl_.rpc_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::celeritas::proto::common::to_gateway_message_header, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::celeritas::proto::common::to_gateway_message_header, _impl_.user_id_),
        PROTOBUF_FIELD_OFFSET(::celeritas::proto::common::to_gateway_message_header, _impl_.rpc_),
        PROTOBUF_FIELD_OFFSET(::celeritas::proto::common::to_gateway_message_header, _impl_.code_),
        0,
        1,
        2,
        0x004, // bitmap
        PROTOBUF_FIELD_OFFSET(::celeritas::proto::common::header, _impl_._oneof_case_[0]),
        PROTOBUF_FIELD_OFFSET(::celeritas::proto::common::header, _impl_.payload_),
        PROTOBUF_FIELD_OFFSET(::celeritas::proto::common::header, _impl_.payload_),
        PROTOBUF_FIELD_OFFSET(::celeritas::proto::common::header, _impl_.payload_),
        PROTOBUF_FIELD_OFFSET(::celeritas::proto::common::header, _impl_.payload_),
        PROTOBUF_FIELD_OFFSET(::celeritas::proto::common::header, _impl_.payload_),
        PROTOBUF_FIELD_OFFSET(::celeritas::proto::common::header, _impl_.payload_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::celeritas::proto::common::empty_message_header)},
        {1, sizeof(::celeritas::proto::common::client_message_header)},
        {6, sizeof(::celeritas::proto::common::server_message_header)},
        {11, sizeof(::celeritas::proto::common::gateway_message_header)},
        {18, sizeof(::celeritas::proto::common::to_gateway_message_header)},
        {27, sizeof(::celeritas::proto::common::header)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::celeritas::proto::common::_empty_message_header_default_instance_._instance,
    &::celeritas::proto::common::_client_message_header_default_instance_._instance,
    &::celeritas::proto::common::_server_message_header_default_instance_._instance,
    &::celeritas::proto::common::_gateway_message_header_default_instance_._instance,
    &::celeritas::proto::common::_to_gateway_message_header_default_instance_._instance,
    &::celeritas::proto::common::_header_default_instance_._instance,
};
const char descriptor_table_protodef_proto_2fcommon_2fcommon_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\031proto/common/common.proto\022\026celeritas.p"
    "roto.common\"\026\n\024empty_message_header\"$\n\025c"
    "lient_message_header\022\013\n\003rpc\030\001 \001(\005\"(\n\025ser"
    "ver_message_header\022\017\n\007user_id\030\001 \001(\003\"6\n\026g"
    "ateway_message_header\022\017\n\007user_id\030\001 \001(\003\022\013"
    "\n\003rpc\030\002 \001(\005\"G\n\031to_gateway_message_header"
    "\022\017\n\007user_id\030\001 \001(\003\022\013\n\003rpc\030\002 \001(\005\022\014\n\004code\030\003"
    " \001(\005\"\340\002\n\006header\022=\n\005empty\030\001 \001(\0132,.celerit"
    "as.proto.common.empty_message_headerH\000\022\?"
    "\n\006client\030\002 \001(\0132-.celeritas.proto.common."
    "client_message_headerH\000\022\?\n\006server\030\003 \001(\0132"
    "-.celeritas.proto.common.server_message_"
    "headerH\000\022A\n\007gateway\030\004 \001(\0132..celeritas.pr"
    "oto.common.gateway_message_headerH\000\022G\n\nt"
    "o_gateway\030\005 \001(\01321.celeritas.proto.common"
    ".to_gateway_message_headerH\000B\t\n\007payloadb"
    "\006proto3"
};
static ::absl::once_flag descriptor_table_proto_2fcommon_2fcommon_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_proto_2fcommon_2fcommon_2eproto = {
    false,
    false,
    647,
    descriptor_table_protodef_proto_2fcommon_2fcommon_2eproto,
    "proto/common/common.proto",
    &descriptor_table_proto_2fcommon_2fcommon_2eproto_once,
    nullptr,
    0,
    6,
    schemas,
    file_default_instances,
    TableStruct_proto_2fcommon_2fcommon_2eproto::offsets,
    file_level_enum_descriptors_proto_2fcommon_2fcommon_2eproto,
    file_level_service_descriptors_proto_2fcommon_2fcommon_2eproto,
};
namespace celeritas {
namespace proto {
namespace common {
// ===================================================================

class empty_message_header::_Internal {
 public:
};

empty_message_header::empty_message_header(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, empty_message_header_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:celeritas.proto.common.empty_message_header)
}
empty_message_header::empty_message_header(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const empty_message_header& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, empty_message_header_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  empty_message_header* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:celeritas.proto.common.empty_message_header)
}

inline void* PROTOBUF_NONNULL empty_message_header::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) empty_message_header(arena);
}
constexpr auto empty_message_header::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(empty_message_header),
                                            alignof(empty_message_header));
}
constexpr auto empty_message_header::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_empty_message_header_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &empty_message_header::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<empty_message_header>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &empty_message_header::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<empty_message_header>(), &empty_message_header::ByteSizeLong,
              &empty_message_header::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(empty_message_header, _impl_._cached_size_),
          false,
      },
      &empty_message_header::kDescriptorMethods,
      &descriptor_table_proto_2fcommon_2fcommon_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull empty_message_header_class_data_ =
        empty_message_header::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
empty_message_header::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&empty_message_header_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(empty_message_header_class_data_.tc_table);
  return empty_message_header_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2>
empty_message_header::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    empty_message_header_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::celeritas::proto::common::empty_message_header>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, // no field_entries, or aux_entries
  {{
  }},
};







::google::protobuf::Metadata empty_message_header::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class client_message_header::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<client_message_header>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(client_message_header, _impl_._has_bits_);
};

client_message_header::client_message_header(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, client_message_header_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:celeritas.proto.common.client_message_header)
}
client_message_header::client_message_header(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const client_message_header& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, client_message_header_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE client_message_header::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void client_message_header::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.rpc_ = {};
}
client_message_header::~client_message_header() {
  // @@protoc_insertion_point(destructor:celeritas.proto.common.client_message_header)
  SharedDtor(*this);
}
inline void client_message_header::SharedDtor(MessageLite& self) {
  client_message_header& this_ = static_cast<client_message_header&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL client_message_header::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) client_message_header(arena);
}
constexpr auto client_message_header::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(client_message_header),
                                            alignof(client_message_header));
}
constexpr auto client_message_header::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_client_message_header_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &client_message_header::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<client_message_header>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &client_message_header::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<client_message_header>(), &client_message_header::ByteSizeLong,
              &client_message_header::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(client_message_header, _impl_._cached_size_),
          false,
      },
      &client_message_header::kDescriptorMethods,
      &descriptor_table_proto_2fcommon_2fcommon_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull client_message_header_class_data_ =
        client_message_header::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
client_message_header::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&client_message_header_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(client_message_header_class_data_.tc_table);
  return client_message_header_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
client_message_header::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(client_message_header, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    client_message_header_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::celeritas::proto::common::client_message_header>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 rpc = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(client_message_header, _impl_.rpc_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(client_message_header, _impl_.rpc_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 rpc = 1;
    {PROTOBUF_FIELD_OFFSET(client_message_header, _impl_.rpc_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void client_message_header::Clear() {
// @@protoc_insertion_point(message_clear_start:celeritas.proto.common.client_message_header)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.rpc_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL client_message_header::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const client_message_header& this_ = static_cast<const client_message_header&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL client_message_header::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const client_message_header& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:celeritas.proto.common.client_message_header)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 rpc = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001U) != 0) {
    if (this_._internal_rpc() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_rpc(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:celeritas.proto.common.client_message_header)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t client_message_header::ByteSizeLong(const MessageLite& base) {
  const client_message_header& this_ = static_cast<const client_message_header&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t client_message_header::ByteSizeLong() const {
  const client_message_header& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:celeritas.proto.common.client_message_header)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // int32 rpc = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (this_._internal_rpc() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_rpc());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void client_message_header::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<client_message_header*>(&to_msg);
  auto& from = static_cast<const client_message_header&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:celeritas.proto.common.client_message_header)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001U) != 0) {
    if (from._internal_rpc() != 0) {
      _this->_impl_.rpc_ = from._impl_.rpc_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void client_message_header::CopyFrom(const client_message_header& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:celeritas.proto.common.client_message_header)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void client_message_header::InternalSwap(client_message_header* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.rpc_, other->_impl_.rpc_);
}

::google::protobuf::Metadata client_message_header::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class server_message_header::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<server_message_header>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(server_message_header, _impl_._has_bits_);
};

server_message_header::server_message_header(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, server_message_header_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:celeritas.proto.common.server_message_header)
}
server_message_header::server_message_header(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const server_message_header& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, server_message_header_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE server_message_header::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void server_message_header::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.user_id_ = {};
}
server_message_header::~server_message_header() {
  // @@protoc_insertion_point(destructor:celeritas.proto.common.server_message_header)
  SharedDtor(*this);
}
inline void server_message_header::SharedDtor(MessageLite& self) {
  server_message_header& this_ = static_cast<server_message_header&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL server_message_header::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) server_message_header(arena);
}
constexpr auto server_message_header::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(server_message_header),
                                            alignof(server_message_header));
}
constexpr auto server_message_header::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_server_message_header_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &server_message_header::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<server_message_header>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &server_message_header::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<server_message_header>(), &server_message_header::ByteSizeLong,
              &server_message_header::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(server_message_header, _impl_._cached_size_),
          false,
      },
      &server_message_header::kDescriptorMethods,
      &descriptor_table_proto_2fcommon_2fcommon_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull server_message_header_class_data_ =
        server_message_header::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
server_message_header::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&server_message_header_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(server_message_header_class_data_.tc_table);
  return server_message_header_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
server_message_header::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(server_message_header, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    server_message_header_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::celeritas::proto::common::server_message_header>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int64 user_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(server_message_header, _impl_.user_id_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(server_message_header, _impl_.user_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 user_id = 1;
    {PROTOBUF_FIELD_OFFSET(server_message_header, _impl_.user_id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void server_message_header::Clear() {
// @@protoc_insertion_point(message_clear_start:celeritas.proto.common.server_message_header)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.user_id_ = ::int64_t{0};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL server_message_header::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const server_message_header& this_ = static_cast<const server_message_header&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL server_message_header::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const server_message_header& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:celeritas.proto.common.server_message_header)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int64 user_id = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001U) != 0) {
    if (this_._internal_user_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<1>(
              stream, this_._internal_user_id(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:celeritas.proto.common.server_message_header)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t server_message_header::ByteSizeLong(const MessageLite& base) {
  const server_message_header& this_ = static_cast<const server_message_header&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t server_message_header::ByteSizeLong() const {
  const server_message_header& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:celeritas.proto.common.server_message_header)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // int64 user_id = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (this_._internal_user_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_user_id());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void server_message_header::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<server_message_header*>(&to_msg);
  auto& from = static_cast<const server_message_header&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:celeritas.proto.common.server_message_header)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001U) != 0) {
    if (from._internal_user_id() != 0) {
      _this->_impl_.user_id_ = from._impl_.user_id_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void server_message_header::CopyFrom(const server_message_header& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:celeritas.proto.common.server_message_header)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void server_message_header::InternalSwap(server_message_header* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.user_id_, other->_impl_.user_id_);
}

::google::protobuf::Metadata server_message_header::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class gateway_message_header::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<gateway_message_header>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(gateway_message_header, _impl_._has_bits_);
};

gateway_message_header::gateway_message_header(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, gateway_message_header_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:celeritas.proto.common.gateway_message_header)
}
gateway_message_header::gateway_message_header(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const gateway_message_header& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, gateway_message_header_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE gateway_message_header::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void gateway_message_header::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, user_id_),
           0,
           offsetof(Impl_, rpc_) -
               offsetof(Impl_, user_id_) +
               sizeof(Impl_::rpc_));
}
gateway_message_header::~gateway_message_header() {
  // @@protoc_insertion_point(destructor:celeritas.proto.common.gateway_message_header)
  SharedDtor(*this);
}
inline void gateway_message_header::SharedDtor(MessageLite& self) {
  gateway_message_header& this_ = static_cast<gateway_message_header&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL gateway_message_header::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) gateway_message_header(arena);
}
constexpr auto gateway_message_header::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(gateway_message_header),
                                            alignof(gateway_message_header));
}
constexpr auto gateway_message_header::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_gateway_message_header_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &gateway_message_header::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<gateway_message_header>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &gateway_message_header::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<gateway_message_header>(), &gateway_message_header::ByteSizeLong,
              &gateway_message_header::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(gateway_message_header, _impl_._cached_size_),
          false,
      },
      &gateway_message_header::kDescriptorMethods,
      &descriptor_table_proto_2fcommon_2fcommon_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull gateway_message_header_class_data_ =
        gateway_message_header::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
gateway_message_header::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&gateway_message_header_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(gateway_message_header_class_data_.tc_table);
  return gateway_message_header_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
gateway_message_header::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(gateway_message_header, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    gateway_message_header_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::celeritas::proto::common::gateway_message_header>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 rpc = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(gateway_message_header, _impl_.rpc_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(gateway_message_header, _impl_.rpc_)}},
    // int64 user_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(gateway_message_header, _impl_.user_id_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(gateway_message_header, _impl_.user_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 user_id = 1;
    {PROTOBUF_FIELD_OFFSET(gateway_message_header, _impl_.user_id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // int32 rpc = 2;
    {PROTOBUF_FIELD_OFFSET(gateway_message_header, _impl_.rpc_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void gateway_message_header::Clear() {
// @@protoc_insertion_point(message_clear_start:celeritas.proto.common.gateway_message_header)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003U) != 0) {
    ::memset(&_impl_.user_id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.rpc_) -
        reinterpret_cast<char*>(&_impl_.user_id_)) + sizeof(_impl_.rpc_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL gateway_message_header::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const gateway_message_header& this_ = static_cast<const gateway_message_header&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL gateway_message_header::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const gateway_message_header& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:celeritas.proto.common.gateway_message_header)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int64 user_id = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001U) != 0) {
    if (this_._internal_user_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<1>(
              stream, this_._internal_user_id(), target);
    }
  }

  // int32 rpc = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002U) != 0) {
    if (this_._internal_rpc() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
              stream, this_._internal_rpc(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:celeritas.proto.common.gateway_message_header)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t gateway_message_header::ByteSizeLong(const MessageLite& base) {
  const gateway_message_header& this_ = static_cast<const gateway_message_header&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t gateway_message_header::ByteSizeLong() const {
  const gateway_message_header& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:celeritas.proto.common.gateway_message_header)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003U) != 0) {
    // int64 user_id = 1;
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (this_._internal_user_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_user_id());
      }
    }
    // int32 rpc = 2;
    if ((cached_has_bits & 0x00000002U) != 0) {
      if (this_._internal_rpc() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_rpc());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void gateway_message_header::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<gateway_message_header*>(&to_msg);
  auto& from = static_cast<const gateway_message_header&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:celeritas.proto.common.gateway_message_header)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003U) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (from._internal_user_id() != 0) {
        _this->_impl_.user_id_ = from._impl_.user_id_;
      }
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      if (from._internal_rpc() != 0) {
        _this->_impl_.rpc_ = from._impl_.rpc_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void gateway_message_header::CopyFrom(const gateway_message_header& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:celeritas.proto.common.gateway_message_header)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void gateway_message_header::InternalSwap(gateway_message_header* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(gateway_message_header, _impl_.rpc_)
      + sizeof(gateway_message_header::_impl_.rpc_)
      - PROTOBUF_FIELD_OFFSET(gateway_message_header, _impl_.user_id_)>(
          reinterpret_cast<char*>(&_impl_.user_id_),
          reinterpret_cast<char*>(&other->_impl_.user_id_));
}

::google::protobuf::Metadata gateway_message_header::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class to_gateway_message_header::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<to_gateway_message_header>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(to_gateway_message_header, _impl_._has_bits_);
};

to_gateway_message_header::to_gateway_message_header(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, to_gateway_message_header_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:celeritas.proto.common.to_gateway_message_header)
}
to_gateway_message_header::to_gateway_message_header(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const to_gateway_message_header& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, to_gateway_message_header_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE to_gateway_message_header::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void to_gateway_message_header::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, user_id_),
           0,
           offsetof(Impl_, code_) -
               offsetof(Impl_, user_id_) +
               sizeof(Impl_::code_));
}
to_gateway_message_header::~to_gateway_message_header() {
  // @@protoc_insertion_point(destructor:celeritas.proto.common.to_gateway_message_header)
  SharedDtor(*this);
}
inline void to_gateway_message_header::SharedDtor(MessageLite& self) {
  to_gateway_message_header& this_ = static_cast<to_gateway_message_header&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL to_gateway_message_header::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) to_gateway_message_header(arena);
}
constexpr auto to_gateway_message_header::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(to_gateway_message_header),
                                            alignof(to_gateway_message_header));
}
constexpr auto to_gateway_message_header::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_to_gateway_message_header_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &to_gateway_message_header::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<to_gateway_message_header>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &to_gateway_message_header::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<to_gateway_message_header>(), &to_gateway_message_header::ByteSizeLong,
              &to_gateway_message_header::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(to_gateway_message_header, _impl_._cached_size_),
          false,
      },
      &to_gateway_message_header::kDescriptorMethods,
      &descriptor_table_proto_2fcommon_2fcommon_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull to_gateway_message_header_class_data_ =
        to_gateway_message_header::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
to_gateway_message_header::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&to_gateway_message_header_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(to_gateway_message_header_class_data_.tc_table);
  return to_gateway_message_header_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2>
to_gateway_message_header::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(to_gateway_message_header, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    to_gateway_message_header_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::celeritas::proto::common::to_gateway_message_header>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int64 user_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(to_gateway_message_header, _impl_.user_id_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(to_gateway_message_header, _impl_.user_id_)}},
    // int32 rpc = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(to_gateway_message_header, _impl_.rpc_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(to_gateway_message_header, _impl_.rpc_)}},
    // int32 code = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(to_gateway_message_header, _impl_.code_), 2>(),
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(to_gateway_message_header, _impl_.code_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 user_id = 1;
    {PROTOBUF_FIELD_OFFSET(to_gateway_message_header, _impl_.user_id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // int32 rpc = 2;
    {PROTOBUF_FIELD_OFFSET(to_gateway_message_header, _impl_.rpc_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 code = 3;
    {PROTOBUF_FIELD_OFFSET(to_gateway_message_header, _impl_.code_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void to_gateway_message_header::Clear() {
// @@protoc_insertion_point(message_clear_start:celeritas.proto.common.to_gateway_message_header)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007U) != 0) {
    ::memset(&_impl_.user_id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.code_) -
        reinterpret_cast<char*>(&_impl_.user_id_)) + sizeof(_impl_.code_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL to_gateway_message_header::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const to_gateway_message_header& this_ = static_cast<const to_gateway_message_header&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL to_gateway_message_header::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const to_gateway_message_header& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:celeritas.proto.common.to_gateway_message_header)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int64 user_id = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001U) != 0) {
    if (this_._internal_user_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<1>(
              stream, this_._internal_user_id(), target);
    }
  }

  // int32 rpc = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002U) != 0) {
    if (this_._internal_rpc() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
              stream, this_._internal_rpc(), target);
    }
  }

  // int32 code = 3;
  if ((this_._impl_._has_bits_[0] & 0x00000004U) != 0) {
    if (this_._internal_code() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
              stream, this_._internal_code(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:celeritas.proto.common.to_gateway_message_header)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t to_gateway_message_header::ByteSizeLong(const MessageLite& base) {
  const to_gateway_message_header& this_ = static_cast<const to_gateway_message_header&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t to_gateway_message_header::ByteSizeLong() const {
  const to_gateway_message_header& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:celeritas.proto.common.to_gateway_message_header)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007U) != 0) {
    // int64 user_id = 1;
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (this_._internal_user_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_user_id());
      }
    }
    // int32 rpc = 2;
    if ((cached_has_bits & 0x00000002U) != 0) {
      if (this_._internal_rpc() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_rpc());
      }
    }
    // int32 code = 3;
    if ((cached_has_bits & 0x00000004U) != 0) {
      if (this_._internal_code() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_code());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void to_gateway_message_header::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<to_gateway_message_header*>(&to_msg);
  auto& from = static_cast<const to_gateway_message_header&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:celeritas.proto.common.to_gateway_message_header)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007U) != 0) {
    if ((cached_has_bits & 0x00000001U) != 0) {
      if (from._internal_user_id() != 0) {
        _this->_impl_.user_id_ = from._impl_.user_id_;
      }
    }
    if ((cached_has_bits & 0x00000002U) != 0) {
      if (from._internal_rpc() != 0) {
        _this->_impl_.rpc_ = from._impl_.rpc_;
      }
    }
    if ((cached_has_bits & 0x00000004U) != 0) {
      if (from._internal_code() != 0) {
        _this->_impl_.code_ = from._impl_.code_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void to_gateway_message_header::CopyFrom(const to_gateway_message_header& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:celeritas.proto.common.to_gateway_message_header)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void to_gateway_message_header::InternalSwap(to_gateway_message_header* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(to_gateway_message_header, _impl_.code_)
      + sizeof(to_gateway_message_header::_impl_.code_)
      - PROTOBUF_FIELD_OFFSET(to_gateway_message_header, _impl_.user_id_)>(
          reinterpret_cast<char*>(&_impl_.user_id_),
          reinterpret_cast<char*>(&other->_impl_.user_id_));
}

::google::protobuf::Metadata to_gateway_message_header::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class header::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::celeritas::proto::common::header, _impl_._oneof_case_);
};

void header::set_allocated_empty(::celeritas::proto::common::empty_message_header* PROTOBUF_NULLABLE empty) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (empty) {
    ::google::protobuf::Arena* submessage_arena = empty->GetArena();
    if (message_arena != submessage_arena) {
      empty = ::google::protobuf::internal::GetOwnedMessage(message_arena, empty, submessage_arena);
    }
    set_has_empty();
    _impl_.payload_.empty_ = empty;
  }
  // @@protoc_insertion_point(field_set_allocated:celeritas.proto.common.header.empty)
}
void header::set_allocated_client(::celeritas::proto::common::client_message_header* PROTOBUF_NULLABLE client) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (client) {
    ::google::protobuf::Arena* submessage_arena = client->GetArena();
    if (message_arena != submessage_arena) {
      client = ::google::protobuf::internal::GetOwnedMessage(message_arena, client, submessage_arena);
    }
    set_has_client();
    _impl_.payload_.client_ = client;
  }
  // @@protoc_insertion_point(field_set_allocated:celeritas.proto.common.header.client)
}
void header::set_allocated_server(::celeritas::proto::common::server_message_header* PROTOBUF_NULLABLE server) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (server) {
    ::google::protobuf::Arena* submessage_arena = server->GetArena();
    if (message_arena != submessage_arena) {
      server = ::google::protobuf::internal::GetOwnedMessage(message_arena, server, submessage_arena);
    }
    set_has_server();
    _impl_.payload_.server_ = server;
  }
  // @@protoc_insertion_point(field_set_allocated:celeritas.proto.common.header.server)
}
void header::set_allocated_gateway(::celeritas::proto::common::gateway_message_header* PROTOBUF_NULLABLE gateway) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (gateway) {
    ::google::protobuf::Arena* submessage_arena = gateway->GetArena();
    if (message_arena != submessage_arena) {
      gateway = ::google::protobuf::internal::GetOwnedMessage(message_arena, gateway, submessage_arena);
    }
    set_has_gateway();
    _impl_.payload_.gateway_ = gateway;
  }
  // @@protoc_insertion_point(field_set_allocated:celeritas.proto.common.header.gateway)
}
void header::set_allocated_to_gateway(::celeritas::proto::common::to_gateway_message_header* PROTOBUF_NULLABLE to_gateway) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_payload();
  if (to_gateway) {
    ::google::protobuf::Arena* submessage_arena = to_gateway->GetArena();
    if (message_arena != submessage_arena) {
      to_gateway = ::google::protobuf::internal::GetOwnedMessage(message_arena, to_gateway, submessage_arena);
    }
    set_has_to_gateway();
    _impl_.payload_.to_gateway_ = to_gateway;
  }
  // @@protoc_insertion_point(field_set_allocated:celeritas.proto.common.header.to_gateway)
}
header::header(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, header_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:celeritas.proto.common.header)
}
PROTOBUF_NDEBUG_INLINE header::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::celeritas::proto::common::header& from_msg)
      : payload_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

header::header(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const header& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, header_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  header* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  switch (payload_case()) {
    case PAYLOAD_NOT_SET:
      break;
      case kEmpty:
        _impl_.payload_.empty_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.empty_);
        break;
      case kClient:
        _impl_.payload_.client_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.client_);
        break;
      case kServer:
        _impl_.payload_.server_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.server_);
        break;
      case kGateway:
        _impl_.payload_.gateway_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.gateway_);
        break;
      case kToGateway:
        _impl_.payload_.to_gateway_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.to_gateway_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:celeritas.proto.common.header)
}
PROTOBUF_NDEBUG_INLINE header::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : payload_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void header::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
header::~header() {
  // @@protoc_insertion_point(destructor:celeritas.proto.common.header)
  SharedDtor(*this);
}
inline void header::SharedDtor(MessageLite& self) {
  header& this_ = static_cast<header&>(self);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  if (this_.has_payload()) {
    this_.clear_payload();
  }
  this_._impl_.~Impl_();
}

void header::clear_payload() {
// @@protoc_insertion_point(one_of_clear_start:celeritas.proto.common.header)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (payload_case()) {
    case kEmpty: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.empty_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.empty_);
      }
      break;
    }
    case kClient: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.client_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.client_);
      }
      break;
    }
    case kServer: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.server_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.server_);
      }
      break;
    }
    case kGateway: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.gateway_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.gateway_);
      }
      break;
    }
    case kToGateway: {
      if (GetArena() == nullptr) {
        delete _impl_.payload_.to_gateway_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.payload_.to_gateway_);
      }
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}


inline void* PROTOBUF_NONNULL header::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) header(arena);
}
constexpr auto header::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(header),
                                            alignof(header));
}
constexpr auto header::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_header_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &header::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<header>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &header::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<header>(), &header::ByteSizeLong,
              &header::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(header, _impl_._cached_size_),
          false,
      },
      &header::kDescriptorMethods,
      &descriptor_table_proto_2fcommon_2fcommon_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull header_class_data_ =
        header::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
header::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&header_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(header_class_data_.tc_table);
  return header_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 5, 5, 0, 2>
header::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    5,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    header_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::celeritas::proto::common::header>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .celeritas.proto.common.empty_message_header empty = 1;
    {PROTOBUF_FIELD_OFFSET(header, _impl_.payload_.empty_), _Internal::kOneofCaseOffset + 0, 0, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .celeritas.proto.common.client_message_header client = 2;
    {PROTOBUF_FIELD_OFFSET(header, _impl_.payload_.client_), _Internal::kOneofCaseOffset + 0, 1, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .celeritas.proto.common.server_message_header server = 3;
    {PROTOBUF_FIELD_OFFSET(header, _impl_.payload_.server_), _Internal::kOneofCaseOffset + 0, 2, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .celeritas.proto.common.gateway_message_header gateway = 4;
    {PROTOBUF_FIELD_OFFSET(header, _impl_.payload_.gateway_), _Internal::kOneofCaseOffset + 0, 3, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .celeritas.proto.common.to_gateway_message_header to_gateway = 5;
    {PROTOBUF_FIELD_OFFSET(header, _impl_.payload_.to_gateway_), _Internal::kOneofCaseOffset + 0, 4, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::celeritas::proto::common::empty_message_header>()},
      {::_pbi::TcParser::GetTable<::celeritas::proto::common::client_message_header>()},
      {::_pbi::TcParser::GetTable<::celeritas::proto::common::server_message_header>()},
      {::_pbi::TcParser::GetTable<::celeritas::proto::common::gateway_message_header>()},
      {::_pbi::TcParser::GetTable<::celeritas::proto::common::to_gateway_message_header>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void header::Clear() {
// @@protoc_insertion_point(message_clear_start:celeritas.proto.common.header)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_payload();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL header::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const header& this_ = static_cast<const header&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL header::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const header& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    this_.VerifyHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:celeritas.proto.common.header)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  switch (this_.payload_case()) {
    case kEmpty: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          1, *this_._impl_.payload_.empty_, this_._impl_.payload_.empty_->GetCachedSize(), target,
          stream);
      break;
    }
    case kClient: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          2, *this_._impl_.payload_.client_, this_._impl_.payload_.client_->GetCachedSize(), target,
          stream);
      break;
    }
    case kServer: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          3, *this_._impl_.payload_.server_, this_._impl_.payload_.server_->GetCachedSize(), target,
          stream);
      break;
    }
    case kGateway: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          4, *this_._impl_.payload_.gateway_, this_._impl_.payload_.gateway_->GetCachedSize(), target,
          stream);
      break;
    }
    case kToGateway: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          5, *this_._impl_.payload_.to_gateway_, this_._impl_.payload_.to_gateway_->GetCachedSize(), target,
          stream);
      break;
    }
    default:
      break;
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:celeritas.proto.common.header)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t header::ByteSizeLong(const MessageLite& base) {
  const header& this_ = static_cast<const header&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t header::ByteSizeLong() const {
  const header& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:celeritas.proto.common.header)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  switch (this_.payload_case()) {
    // .celeritas.proto.common.empty_message_header empty = 1;
    case kEmpty: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.empty_);
      break;
    }
    // .celeritas.proto.common.client_message_header client = 2;
    case kClient: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.client_);
      break;
    }
    // .celeritas.proto.common.server_message_header server = 3;
    case kServer: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.server_);
      break;
    }
    // .celeritas.proto.common.gateway_message_header gateway = 4;
    case kGateway: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.gateway_);
      break;
    }
    // .celeritas.proto.common.to_gateway_message_header to_gateway = 5;
    case kToGateway: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_.to_gateway_);
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void header::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<header*>(&to_msg);
  auto& from = static_cast<const header&>(from_msg);
  if constexpr (::_pbi::DebugHardenVerifyHasBitConsistency()) {
    from.VerifyHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:celeritas.proto.common.header)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_payload();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kEmpty: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.empty_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.empty_);
        } else {
          _this->_impl_.payload_.empty_->MergeFrom(*from._impl_.payload_.empty_);
        }
        break;
      }
      case kClient: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.client_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.client_);
        } else {
          _this->_impl_.payload_.client_->MergeFrom(*from._impl_.payload_.client_);
        }
        break;
      }
      case kServer: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.server_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.server_);
        } else {
          _this->_impl_.payload_.server_->MergeFrom(*from._impl_.payload_.server_);
        }
        break;
      }
      case kGateway: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.gateway_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.gateway_);
        } else {
          _this->_impl_.payload_.gateway_->MergeFrom(*from._impl_.payload_.gateway_);
        }
        break;
      }
      case kToGateway: {
        if (oneof_needs_init) {
          _this->_impl_.payload_.to_gateway_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.payload_.to_gateway_);
        } else {
          _this->_impl_.payload_.to_gateway_->MergeFrom(*from._impl_.payload_.to_gateway_);
        }
        break;
      }
      case PAYLOAD_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void header::CopyFrom(const header& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:celeritas.proto.common.header)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void header::InternalSwap(header* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.payload_, other->_impl_.payload_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata header::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace common
}  // namespace proto
}  // namespace celeritas
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_proto_2fcommon_2fcommon_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
