syntax = "proto3";

package celeritas.proto.client;

message login_request {
    string token = 1;
    string game_server_id = 2;
    string device_id = 3;
    string app_version = 4;
}

message login_response {
    int64 current_time = 1;
}

message login_finish_response {
}

message error_response {
}

message client_login_request {
  oneof payload {
    login_request login = 1;
  }
}

message client_login_response {
  oneof payload {
    login_response login = 1;
    login_finish_response login_finish = 2;
    error_response error = 3;
  }
}


