syntax = "proto3";

package celeritas.proto.client;

import "proto/common/item.proto";

message mail_data {
    int64 mail_id = 1;
    int32 type = 2;
    bool multilingual = 3;
    string title = 4;
    string content = 5;
    int64 send_time = 6;
    int64 expire_time = 7;
    bool read = 8;
    bool attachment_collected = 9;
    repeated common.inventory_data attachments = 10;
}

message mail_request {
    int64 max_mail_id = 1;
    int32 language_type = 2;
}

message mail_response {
    repeated mail_data mail = 1;
}

message mail_read_request {
    int64 mail_id = 1;
}

message mail_read_response {
    int64 mail_id = 1;
}

message mail_collect_attachment_request {
    int64 mail_id = 1;
}

message mail_collect_attachment_response {
    int64 mail_id = 1;
}

message mail_delete_request {
    int64 mail_id = 1;
}

message mail_delete_response {
    int64 mail_id = 1;
}

message mail_collect_all_attachments_request {
}

message mail_collect_all_attachments_response {
    repeated int64 mail_ids = 1;
}

message mail_delete_all_read_request {
}

message mail_delete_all_read_response {
    repeated int64 mail_ids = 1;
}

message client_mail_request {
  oneof payload {
    mail_request mail = 1;
    mail_read_request mail_read = 2;
    mail_collect_attachment_request mail_collect_attachment = 3;
    mail_delete_request mail_delete = 4;
    mail_collect_all_attachments_request mail_collect_all_attachments = 5;
    mail_delete_all_read_request mail_delete_all_read = 6;
  }
}

message client_mail_response {
  oneof payload {
    mail_response mail = 1;
    mail_read_response mail_read = 2;
    mail_collect_attachment_response mail_collect_attachment = 3;
    mail_delete_response mail_delete = 4;
    mail_collect_all_attachments_response mail_collect_all_attachments = 5;
    mail_delete_all_read_response mail_delete_all_read = 6;
  }
}