syntax = "proto3";

package celeritas.proto.client;

import "proto/client/player/login.proto";
import "proto/client/player/heartbeat.proto";
import "proto/client/player/role.proto";
import "proto/client/player/red_dot.proto";
import "proto/client/player/item.proto";
import "proto/client/player/error.proto";

message client_player_request {
  oneof payload {
    client_login_request login = 1;
    client_heartbeat_request heartbeat = 2;
    client_role_request role = 3;
  }
}

message client_player_response {
  oneof payload {
    client_login_response login = 1;
    client_heartbeat_response heartbeat = 2;
    client_error_response error = 3;
    client_role_response role = 4;
    client_red_dot_response red_dot = 5;
    client_item_response item = 6;
  }
}
