// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/celeritas.proto
// Protobuf C++ Version: 6.32.1

#ifndef proto_2fceleritas_2eproto_2epb_2eh
#define proto_2fceleritas_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6032001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "proto/request.pb.h"
#include "proto/response.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_proto_2fceleritas_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2fceleritas_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_proto_2fceleritas_2eproto;
}  // extern "C"
namespace celeritas {
namespace proto {
class celeritas;
struct celeritasDefaultTypeInternal;
extern celeritasDefaultTypeInternal _celeritas_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull celeritas_class_data_;
}  // namespace proto
}  // namespace celeritas
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace celeritas {
namespace proto {

// ===================================================================


// -------------------------------------------------------------------

class celeritas final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:celeritas.proto.celeritas) */ {
 public:
  inline celeritas() : celeritas(nullptr) {}
  ~celeritas() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(celeritas* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(celeritas));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR celeritas(::google::protobuf::internal::ConstantInitialized);

  inline celeritas(const celeritas& from) : celeritas(nullptr, from) {}
  inline celeritas(celeritas&& from) noexcept
      : celeritas(nullptr, ::std::move(from)) {}
  inline celeritas& operator=(const celeritas& from) {
    CopyFrom(from);
    return *this;
  }
  inline celeritas& operator=(celeritas&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const celeritas& default_instance() {
    return *reinterpret_cast<const celeritas*>(
        &_celeritas_default_instance_);
  }
  enum PayloadCase {
    kCeleritasRequest = 1,
    kCeleritasResponse = 2,
    PAYLOAD_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(celeritas& a, celeritas& b) { a.Swap(&b); }
  inline void Swap(celeritas* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(celeritas* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  celeritas* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<celeritas>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const celeritas& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const celeritas& from) { celeritas::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(celeritas* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "celeritas.proto.celeritas"; }

 protected:
  explicit celeritas(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  celeritas(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const celeritas& from);
  celeritas(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, celeritas&& from) noexcept
      : celeritas(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCeleritasRequestFieldNumber = 1,
    kCeleritasResponseFieldNumber = 2,
  };
  // .celeritas.proto.request celeritas_request = 1;
  bool has_celeritas_request() const;
  private:
  bool _internal_has_celeritas_request() const;

  public:
  void clear_celeritas_request() ;
  const ::celeritas::proto::request& celeritas_request() const;
  [[nodiscard]] ::celeritas::proto::request* PROTOBUF_NULLABLE release_celeritas_request();
  ::celeritas::proto::request* PROTOBUF_NONNULL mutable_celeritas_request();
  void set_allocated_celeritas_request(::celeritas::proto::request* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_celeritas_request(::celeritas::proto::request* PROTOBUF_NULLABLE value);
  ::celeritas::proto::request* PROTOBUF_NULLABLE unsafe_arena_release_celeritas_request();

  private:
  const ::celeritas::proto::request& _internal_celeritas_request() const;
  ::celeritas::proto::request* PROTOBUF_NONNULL _internal_mutable_celeritas_request();

  public:
  // .celeritas.proto.response celeritas_response = 2;
  bool has_celeritas_response() const;
  private:
  bool _internal_has_celeritas_response() const;

  public:
  void clear_celeritas_response() ;
  const ::celeritas::proto::response& celeritas_response() const;
  [[nodiscard]] ::celeritas::proto::response* PROTOBUF_NULLABLE release_celeritas_response();
  ::celeritas::proto::response* PROTOBUF_NONNULL mutable_celeritas_response();
  void set_allocated_celeritas_response(::celeritas::proto::response* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_celeritas_response(::celeritas::proto::response* PROTOBUF_NULLABLE value);
  ::celeritas::proto::response* PROTOBUF_NULLABLE unsafe_arena_release_celeritas_response();

  private:
  const ::celeritas::proto::response& _internal_celeritas_response() const;
  ::celeritas::proto::response* PROTOBUF_NONNULL _internal_mutable_celeritas_response();

  public:
  void clear_payload();
  PayloadCase payload_case() const;
  // @@protoc_insertion_point(class_scope:celeritas.proto.celeritas)
 private:
  class _Internal;
  void set_has_celeritas_request();
  void set_has_celeritas_response();
  inline bool has_payload() const;
  inline void clear_has_payload();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 2,
                                   2, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const celeritas& from_msg);
    union PayloadUnion {
      constexpr PayloadUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::celeritas::proto::request* PROTOBUF_NULLABLE celeritas_request_;
      ::celeritas::proto::response* PROTOBUF_NULLABLE celeritas_response_;
    } payload_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fceleritas_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull celeritas_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// celeritas

// .celeritas.proto.request celeritas_request = 1;
inline bool celeritas::has_celeritas_request() const {
  return payload_case() == kCeleritasRequest;
}
inline bool celeritas::_internal_has_celeritas_request() const {
  return payload_case() == kCeleritasRequest;
}
inline void celeritas::set_has_celeritas_request() {
  _impl_._oneof_case_[0] = kCeleritasRequest;
}
inline ::celeritas::proto::request* PROTOBUF_NULLABLE celeritas::release_celeritas_request() {
  // @@protoc_insertion_point(field_release:celeritas.proto.celeritas.celeritas_request)
  if (payload_case() == kCeleritasRequest) {
    clear_has_payload();
    auto* temp = _impl_.payload_.celeritas_request_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.celeritas_request_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::celeritas::proto::request& celeritas::_internal_celeritas_request() const {
  return payload_case() == kCeleritasRequest ? *_impl_.payload_.celeritas_request_ : reinterpret_cast<::celeritas::proto::request&>(::celeritas::proto::_request_default_instance_);
}
inline const ::celeritas::proto::request& celeritas::celeritas_request() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:celeritas.proto.celeritas.celeritas_request)
  return _internal_celeritas_request();
}
inline ::celeritas::proto::request* PROTOBUF_NULLABLE celeritas::unsafe_arena_release_celeritas_request() {
  // @@protoc_insertion_point(field_unsafe_arena_release:celeritas.proto.celeritas.celeritas_request)
  if (payload_case() == kCeleritasRequest) {
    clear_has_payload();
    auto* temp = _impl_.payload_.celeritas_request_;
    _impl_.payload_.celeritas_request_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void celeritas::unsafe_arena_set_allocated_celeritas_request(
    ::celeritas::proto::request* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_celeritas_request();
    _impl_.payload_.celeritas_request_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:celeritas.proto.celeritas.celeritas_request)
}
inline ::celeritas::proto::request* PROTOBUF_NONNULL celeritas::_internal_mutable_celeritas_request() {
  if (payload_case() != kCeleritasRequest) {
    clear_payload();
    set_has_celeritas_request();
    _impl_.payload_.celeritas_request_ = 
        ::google::protobuf::Message::DefaultConstruct<::celeritas::proto::request>(GetArena());
  }
  return _impl_.payload_.celeritas_request_;
}
inline ::celeritas::proto::request* PROTOBUF_NONNULL celeritas::mutable_celeritas_request()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::celeritas::proto::request* _msg = _internal_mutable_celeritas_request();
  // @@protoc_insertion_point(field_mutable:celeritas.proto.celeritas.celeritas_request)
  return _msg;
}

// .celeritas.proto.response celeritas_response = 2;
inline bool celeritas::has_celeritas_response() const {
  return payload_case() == kCeleritasResponse;
}
inline bool celeritas::_internal_has_celeritas_response() const {
  return payload_case() == kCeleritasResponse;
}
inline void celeritas::set_has_celeritas_response() {
  _impl_._oneof_case_[0] = kCeleritasResponse;
}
inline ::celeritas::proto::response* PROTOBUF_NULLABLE celeritas::release_celeritas_response() {
  // @@protoc_insertion_point(field_release:celeritas.proto.celeritas.celeritas_response)
  if (payload_case() == kCeleritasResponse) {
    clear_has_payload();
    auto* temp = _impl_.payload_.celeritas_response_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.payload_.celeritas_response_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::celeritas::proto::response& celeritas::_internal_celeritas_response() const {
  return payload_case() == kCeleritasResponse ? *_impl_.payload_.celeritas_response_ : reinterpret_cast<::celeritas::proto::response&>(::celeritas::proto::_response_default_instance_);
}
inline const ::celeritas::proto::response& celeritas::celeritas_response() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:celeritas.proto.celeritas.celeritas_response)
  return _internal_celeritas_response();
}
inline ::celeritas::proto::response* PROTOBUF_NULLABLE celeritas::unsafe_arena_release_celeritas_response() {
  // @@protoc_insertion_point(field_unsafe_arena_release:celeritas.proto.celeritas.celeritas_response)
  if (payload_case() == kCeleritasResponse) {
    clear_has_payload();
    auto* temp = _impl_.payload_.celeritas_response_;
    _impl_.payload_.celeritas_response_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void celeritas::unsafe_arena_set_allocated_celeritas_response(
    ::celeritas::proto::response* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_payload();
  if (value) {
    set_has_celeritas_response();
    _impl_.payload_.celeritas_response_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:celeritas.proto.celeritas.celeritas_response)
}
inline ::celeritas::proto::response* PROTOBUF_NONNULL celeritas::_internal_mutable_celeritas_response() {
  if (payload_case() != kCeleritasResponse) {
    clear_payload();
    set_has_celeritas_response();
    _impl_.payload_.celeritas_response_ = 
        ::google::protobuf::Message::DefaultConstruct<::celeritas::proto::response>(GetArena());
  }
  return _impl_.payload_.celeritas_response_;
}
inline ::celeritas::proto::response* PROTOBUF_NONNULL celeritas::mutable_celeritas_response()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::celeritas::proto::response* _msg = _internal_mutable_celeritas_response();
  // @@protoc_insertion_point(field_mutable:celeritas.proto.celeritas.celeritas_response)
  return _msg;
}

inline bool celeritas::has_payload() const {
  return payload_case() != PAYLOAD_NOT_SET;
}
inline void celeritas::clear_has_payload() {
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}
inline celeritas::PayloadCase celeritas::payload_case() const {
  return celeritas::PayloadCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace celeritas


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // proto_2fceleritas_2eproto_2epb_2eh
